### ISSUE TITLE
JAWS can't read input fields and buttons inside layout tables

### ISSUE THREAD

**Issue by yugu0114** [FreedomScientific/standards-support#108]
### Summary
JAWS can't read input fields and buttons inside layout tables (with role="presentation" or role="none").
> Hi, we have complex mark-up, so we tried to make example in the most simple way as possible. 

There are several layout tables. 

The first is used for position of toolbar and table (there is no toolbar in the example). 

The second table is used for presentation data and it has wrapper <div role="application"> to perform navigation (otherwise JAWS doesn't turn in form mode from virtual pc cursor so an user can't navigate through table by custom keys). 

Also we have layout tables in table head. There we have list of sub actions for column and one of the list items opens sorting popup (in the example the popup is colored in green). 

And we use <div role="dialog"> inside <td> of data table to perform changes in grid mode. 

So there is problem that JAWS can't read title of active elements in sorting popup (green elements) and ingrid dialog (white elements) but it reads a lot of extra information. Unfortunately, we can't draw this 2 popup dialogues out of the table, so could you please take a look of the issue.
> 
> Example:
> 1. Go to http://output.jsbin.com/bujapikena in IE11
> 2. Naigate to input fields and buttons inside table

### Expected result

> Nested buttons and inputs are read correctly with linked label or by title/aria-label parameter.

### Actual result

> JAWS reads extra information, for e.x. upper div (if <input id="1"> receives the focus). Or reads only "Not in a table" when focus is set on Apply button.

### Example

> http://output.jsbin.com/bujapikena 

#### JAWS version and build number

JAWS 17 v.17.0.2729.400
JAWS 18 v.18.0.4104.400
 
#### Operating System and version

Windows 10 pro

#### Browser and version:

IE 11 v.11.1266.15063.0

**Comment by stevefaulkner** [comment]
created codepen version of test case https://codepen.io/stevef/pen/wEJWMd

**Comment by stevefaulkner** [comment]
legacy IE bug - wontfix
