### ISSUE TITLE
JAWS announces filename for image when ancestor has onclick handler even though image has null alt in Firefox

### ISSUE THREAD

**Issue by mraccess77** [FreedomScientific/standards-support#123]
### Summary
JAWS announces filename for image when ancestor has onclick handler even though image has null alt.  I understand that for clickable images it would be the case -- but in this case the click handler is on an ancestor and has nothing to do with the image.  Angular and other frameworks commonly apply handlers on the body element.  This isn't an issue for Chrome and IE.
https://labs.levelaccess.com/index.php/Image_with_null_alt

### Expected result
The image would be skipped because it is decorative.

### Actual result
The image filename is announced.

### Example
https://labs.levelaccess.com/index.php/Image_with_null_alt 

#### JAWS version and build number
JAWS2018.1808

 #### Operating System and version
Windows 7 and 10

#### Browser and version:
Firefox 62

**Comment by willslone** [comment]
Tested using JAWS Version 2020.2004.66 and Firefox 77 and the issue is still present.

**Comment by jducrot** [comment]
https://cdpn.io/TPG/debug/7547ba652e85af87305a713c99f08c2b
