### ISSUE TITLE
SVG not announced with Firefox 62  and JAWS 2018

### ISSUE THREAD

**Issue by brooksienoodlesoup** [FreedomScientific/standards-support#128]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
> 1. I've used accessible best practices to expose an SVG icon to JAWS by adding `title` text, as well as using `aria-labelledby` on the `svg` element. 
> I can't get Firefox 62.0.3 +  JAWS 2018.1808.10 to announce the presence of the `svg` in the following code snippet.  It is skipped, as if it isn't in the accessibility tree.

### Expected result

> What did you expect to happen?
I expected to be able hear the announcement of a "More options" graphic by either browsing with the virtual pc cursor through the page content, or by using the "G" keystroke to navigate to images on the page.  

### Actual result

> What actually did happen?
Neither method browsing with the virtual pc cursor or navigating by the "G" keystroke announces the existence of the <svg> in the code.

### Example

> 
```html
<svg fit="" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" focusable="false"
role=”img” aria-labelledby=”title”>
    <title id=”title”>Caution</title>
    <g id="svg-Caution-container" transform="translate(1 3)">
        <path id="svg-Caution-shape" d="M0 19h22L11 0 0 19zm12-3h-2v-2h2v2zm0-4h-  
        2V8h2v4z"></path>
    </g>
    <path id="svg-Artboard" fill="none" d="M0 0h24v24H0z"></path>
</svg>
```

#### JAWS version and build number
JAWS 2018.1808.10

 
#### Operating System and version
Windows 7 version 6.1 

#### Browser and version:
Firefox 62.0.3

**Comment by lamador** [comment]
Issue is confirmed using JAWS 2020.2004.66 and Firefox 76.0.1 (64-bit) on Windows 10.

**Comment by stevefaulkner** [comment]
@lamador the example code for this issue provided by @brooksienoodlesoup includes `aria-labelledby=”title”` the test case used does not?

**Comment by stevefaulkner** [comment]
tested with JAWS 2023.2307.37 and firefox 117.0b6 (64-bit), works as expected, announced as graphic with acc name
[test case](https://cdpn.io/pen/debug/QWJeMYB)
