### ISSUE TITLE
Combox not working when using certain aria-label

### ISSUE THREAD

**Issue by timotheeguerin** [FreedomScientific/standards-support#135]
### Summary

This issue is very weird. I have a custom select which define a wrapper element(role=combobox) and a button(role=textbox) which gets replaced with a input if the select is filterable. Now it seems like that depending on the label given to the wrapper element it doesn't seem to describe the combobox(Or even focus it)

### Expected result

When pressing tab to focus on the combobox is focus it and describe it correctly

### Actual result
The previous selection is being described.
It seems like the combobox is focused in the UI(Show the outline) but JAWS doesn't actually focus it. 
i.e. When pressing enter after it activate the button not the combobox

### Example

Repro https://jsfiddle.net/g3wy50tz/
Here there is 2 combox. First is not working, Second is working fine. Only difference is the aria-label. For the first `Time` for the second `Time range that works`

This repo is just with copied the static html(It is not actually working as a combox here) but it should still let me focus the combox and describe it

### Additional Information
It seems to be based on the length of the `aria-label` 

#### JAWS version and build number
JAWS 2018 1808.10

 
#### Operating System and version
Windows 10 

#### Browser and version:
Chrome

**Comment by JAWS-test** [comment]
Up to 13 characters in the aria-label the error occurs, above 14 characters it does not occur. The text content in the aria-label does not seem to matter, it really only depends on the length.
