### ISSUE TITLE
Regression: role="table" conflicts with tabindex in IE11 starting with JAWS 2018

### ISSUE THREAD

**Issue by MichaelKetting** [FreedomScientific/standards-support#145]
### Summary

1. Use ARIA roles ('table', etc) to construct a single, cohesive table from two separate table structures, e.g. if you need to separate the header-row from the body so you can provide a scrollable tbody with a fixed thead.
2. Apply the 'tabindex' attribute to the element with role="table" or its parent or any ancestor.
3. Step through the page's tables using the 't' key in browse mode. 
4. Navigate the table using the cursor-keys.

### Expected result

1. The constructed table will be announced as a single, cohesive table.
2. The cells are announced with their respective column headers to provide orientation.

### Actual result

1. The constructed table is announced as two separate tables when using JAWS 2018 or 2019 with Internet Explorer 11
2. The individual cells are also not prefixed with the column header when they are announced while navigating a specific table when using JAWS 2018 or 2019 with Internet Explorer 11.

### Example

https://codepen.io/anon/pen/JezPKM
or
[TestPage.zip](https://github.com/FreedomScientific/VFO-standards-support/files/2637202/TestPage.zip)

### Additional Information

This combination of DOM attributes used to work in JAWS v18 and continues to work when using Microsoft Edge, Google Chrome, or Mozilla Firefox in JAWS 2018 and JAWS 2019.

#### JAWS version and build number
JAWS 18.0.5038
JAWS 2018.1808.10
JAWS 2019.1810.64
 
#### Operating System and version
Windows 10 v1709 (OS Build 16299.785)

#### Browser and version:
Internet Explorer 11.785.16299.0 (Update version 11.0.95)
Microsoft Edge 41.16299.785.0
Mozilla Firefox 63.0.3
Google Chrome: 70.0.3538.110

**Comment by MichaelKetting** [comment]
@stevefaulkner is there any update on this regression issue?

**Comment by stevefaulkner** [comment]
Have asked @ggordon-vfo to review

**Comment by JAWS-test** [comment]
The problem persists

**Comment by stevefaulkner** [comment]
IE only, closing
