### ISSUE TITLE
JAWS ignores alt="" on img elements nested inside <label for="id-of-input">

### ISSUE THREAD

**Issue by mra11yx** [FreedomScientific/standards-support#147]
### Summary

> 1. Open JAWS and open FF 63 on Windows 10
> 2. Go to https://codepen.io/mra11yx/pen/zMVPJP (fork and enable debug mode if needed)
> 3. Navigate through the document using the virtual cursor

### Expected result

> JAWS should ignore the images because they have alt="" set, and the input that each label refers to already has an accessible name (via aria-label)

### Actual result

> JAWS attempts to calculate accessible names for the images, and reads their filenames

### Example

> https://codepen.io/mra11yx/pen/zMVPJP

### Additional Information
Issue does not happen in IE11, and does not happen when using FF with NVDA.

#### JAWS version and build number
2018.1811.2

 
#### Operating System and version
Windows 10, 64-bit

#### Browser and version:
Firefox 63.0.3, 64-bit

**Comment by stevefaulkner** [comment]
@mra11yx can reproduce with Firefox and JAWS 2019. 

Although this is indeed a bug in JAWS, your statement:

> This happens even if the input element is labeled properly using aria-label.

is a problematic one as you provide a native labelling mechanism using the `label` element, but put no text content in it:

```
<label for="set03_03">
    <input type="radio" name="set03" id="set03_03" aria-label="generic PC"><img src="https://upload.wikimedia.org/wikipedia/commons/5/56/Computer_icon.png" alt="" height="40px">
  </label>
```
  As in this case the image is informative and is used as the content of the label the more appropriate markup would be to provide a text alternative for the image:

```
<label for="set03_03">
    <input type="radio" name="set03" id="set03_03" ><img src="https://upload.wikimedia.org/wikipedia/commons/5/56/Computer_icon.png" alt="generic PC" height="40px">
  </label>
```
This pattern improves the accessibility of the content while also resolving the particular case in which the JAWS bug manifests itself.

There is still an issue though as this markup relies upon the user being able to identify the hardware in the image correctly, without the text alternative I would have known what each of the images represent. I suggest the most appropriate markup pattern would be:

```
<label for="set03_03">
    <input type="radio" name="set03" id="set03_03" ><img src="https://upload.wikimedia.org/wikipedia/commons/5/56/Computer_icon.png" alt="" height="40px">
generic PC
  </label>
```
In this case the text label is available to all. But this also reintroduces the JAWS bug as the `<img>` is announced as well as the text label. This can be mitigated by using `aria-hidden="true"` although JAWS bug specific workarounds are not encouranged as they result in extra work and extra code for developers.

```
<label for="set03_03">
    <input type="radio" name="set03" id="set03_03" ><img src="https://upload.wikimedia.org/wikipedia/commons/5/56/Computer_icon.png" `alt=""` height="40px">
generic PC
  </label>
```

**Comment by stevefaulkner** [comment]
@mra11yx internal bug filed "Bug 106124 - JAWS ignores alt="" on img elements nested inside <label for="id-of-input"> "

**Comment by JAWS-test** [comment]
The problem continues to occur with current JAWS 2019. The graphics are also reached by G and displayed in INS+Ctrl+G with their URL. According to https://www.w3.org/TR/accname-1.1/ aria-label should be output with higher priority than label, so the label should be ignored.
