### ISSUE TITLE
MathML is never spoken correctly when encountered using the tab key

### ISSUE THREAD

**Issue by pbblair** [FreedomScientific/standards-support#148]
### Summary

1. Go to [http://superkeen.com/web/mathmltest/mathmlfocus.html](http://superkeen.com/web/mathmltest/mathmlfocus.html)
2. Tab through the page.

### Expected result

MathML mixed with plain text should be spoken correctly many times as:
>The fraction two thirds and the exponent two cubed are not equal.

### Actual result

MathML is spoken incorrectly as:
>The fraction and the exponent are not equal.

or
>The fraction x and the exponent x are not equal.

### Example

The link provided above provides multiple examples.  It's a standalone HTML file without any CSS or Javascript, so it should be easy enough to View Source or to download it.

### Additional Information

I am trying to write a math game that students can play entirely with the tab key, but for it to work with JAWS, this issue would need to be resolved.  As it is now, it seems that there is virtually no way for JAWS to speak MathML without using JAWS shortcuts to read from the virtual buffer.  It would be ideal for content within the "math" element to be routed through the appropriate speech rule engine regardless of its context.

Issue #25 is related, but more focused on list item labels.  My concern is on the complete absence of MathML support when using the tab key.

I have filed a very similar bug report to Orca: https://gitlab.gnome.org/GNOME/orca/issues/26

#### JAWS version and build number

JAWS 2019 1810.64 ILM
 
#### Operating System and version

Windows 10 Pro N Version 1803

#### Browser and version:

Firefox 63.0.3 (64-bit) and Chrome 71.0.3578.80 (64-bit)

**Comment by pbblair** [comment]
Test case page has been updated to reflect the fact that Orca support has been improved.

**Comment by stevefaulkner** [comment]
JAWS 2023.2307.37 and Chrome Version 115.0.5790.171 (Official Build) (64-bit)
tested using https://cdpn.io/pen/debug/WNLeOxe 

- tab to the second instance
- JAWS announces  "The fraction" 
- press arrow down "The fraction 2 thirds and the exponent 2 cubed are not equal.

works as expected for me.
