### ISSUE TITLE
JAWS not reading table title when tabbing between 2 editable table

### ISSUE THREAD

**Issue by timotheeguerin** [FreedomScientific/standards-support#150]
### Summary

When having inputs in cells of a table JAWS and having 2 of those tables one after the other. When tabbing between the last cell of the first table to the first cell of the next one, JAWS doesn't anounce the title of the 2nd table.

### Expected result

JAWS should read the title of the newly focused table

### Actual result

JAWS just reads the name of the column for the input

### Example

2 table next to each other. When focusing the table for the first time it announce the title just fine. When navigating between table it fail to anounce the new table title.
https://jsfiddle.net/L32uszmv/

#### JAWS version and build number
JAWS 2018 1811.2 ILM

#### Operating System and version
Windows 10

#### Browser and version:
Chrome `Version 70.0.3538.110 (Official Build) (64-bit)`

**Comment by stevefaulkner** [comment]
reproduced with chrome 72 and jaws 2019

**Comment by stevefaulkner** [comment]
internal bug filed: Bug 106331 - JAWS not reading table caption when tabbing between 2 tables

**Comment by stevefaulkner** [comment]
tested with JAWS 2023.2307.37, problem still present but the table captions are announced using table commands and other virtual cursor navigation, so calling this as wontfix
