### ISSUE TITLE
Aria-Live error message for an on blur() event is announced after focus is already received on another field

### ISSUE THREAD

**Issue by bestuiexperience** [FreedomScientific/standards-support#153]
### Summary

I am working on an application using aria-live. I have an blur event on a field that causes text to be populated in an aria-alive region. I am expecting the aria-live text to be read before the label text to the second field that is being focused on is read. Instead, the second field's label is read out before the first field's error message. This is very confusing behavior. NVDA is working as expected. 

I tested the example below with JAWS 2019.1810.64ILM. Same results found in Chrome, Firefox and IE11 on a Windows 10 platform.

Please try the example below:

https://jsbin.com/sebegotiga/edit?html,css,js,output

Perform the following Steps:

1. Tab into the First Name field with he virtual cursor off. Do not enter a first name.
2. Tab  into the Last Name field. You will hear an announcement announcing the label for the last name field and indicating that it is required and editable. And then you will hear " Please enter a first name."
3. The behavior that I would have expected is that the user would first hear "Please enter a first name." because they had just tabbed away from the first name field without entering any data. After that I would expect to hear the label for the last name.

NVDA works exactly as I would have expected.

**Comment by bestuiexperience** [comment]
Are there any updates on this issue? Because of the improper sequence of when on blur() events are announced it is impossible to deliver in-place validation without confusing users.

**Comment by stevefaulkner** [comment]
created [codepen version of test case](https://codepen.io/stevef/pen/dweOvL)

**Comment by bestuiexperience** [comment]
Are there any updates on this issue?

**Comment by JAWS-test** [comment]
I only know that aria-live does not work correctly in IE 11 with JAWS. aria-live=assertive is only output with higher priority than aria-live=polite, but not before normal screenreader output (https://www.w3.org/TR/wai-aria-1.1/#aria-live). To output a message before the normal screenreader output, role=alert must be used (https://www.w3.org/TR/wai-aria-1.1/#alert). However, role=alert interrupts the current screenreader output, which is also no longer output afterwards.

I suspect that there is no perfect solution for automatic validation. For accessibility, it would be important that the validation is clearly perceptible with the screen reader and efficiently operable after submitting the form.

**Comment by stevefaulkner** [comment]
recommend use of `role=alert` for this use case

**Comment by emilieviau** [comment]
Unfortunately, this solution is partial. For example, it works with JAWS in combination with Firefox, but not with Chrome and Edge.

Test environment:

- Windows 11
- Chrome 133.0.6943.54
- Firefox 135
- Edge 132.0.2957.140
- JAWS 2022 to 2025
