### ISSUE TITLE
Button action and announcement is incorrect

### ISSUE THREAD

**Issue by vagdwd** [FreedomScientific/standards-support#187]
### Summary
A dialog with role=dialog and two buttons - Cancel and Submit results in incorrect action and wrong label announced.

### Expected result
I expect the buttons to tab correctly from cancel to submit and vice-versa.

### Actual result
Though in UI the focus changes between buttons on tabbing and shift-tabbing, but the reader announcement and the actual action (pressing enter key) always refers to the first button. Same functionality works fine when JAWS isn't running. 

#### JAWS version and build number
JAWS 18.0.5038

#### Operating System and version
Windows 10

#### Browser and version:
IE v11.648.17134.0

**Comment by scottaohara** [comment]
@vagdwd, could you please provide a test case?

**Comment by stevefaulkner** [comment]
closing as no test case provided.
