### ISSUE TITLE
JAWS 2018 reads all elements of AutoComplete as “blank” while navigating using up and down arrow keys through the autocomplete result.

### ISSUE THREAD

**Issue by sunilsutar** [FreedomScientific/standards-support#190]
### Summary

> Brief description of the issue. Please list any specific steps.
> 
> Example:
Details:
Product: JAWS 2018.1811.2ILM and 2019 latest
Please refer 
https://demos.telerik.com/aspnet-ajax/autocompletebox/examples/accessibility-and-internationalization/wai-aria-support/defaultcs.aspx
or the sample attached herewith - as RadAutoCompleteNonDBDemo.aspx with 3 files.

Start JAWS 2018 or JAWS 2019
Type “a”  in the autocomplete in any of the above example.
Observe the result list.
Press Down Arrow to go through and navigate through the list.
Observer JAWS reads it as “blank”, “blank”, “blank” while going through each element.

Expected: JAWS 2018 and 2019 should mention each element that user is navigating.
With JAWS 18 it works as expected for the same samples.

### Expected result

> What did you expect to happen?
Like the earlier version of JAWS 17 or 18, it should read the element as user is navigating through the list.
e.g. there is another issue that I found related to ul-li and I believe this is the same for the above behavior. https://github.com/FreedomScientific/VFO-standards-support/issues/50

### Actual result

> What actually did happen?
JAWS reads as "blank" "blank" "blank" when user press down/up arrow to navigate through list.
### Example
https://demos.telerik.com/aspnet-ajax/autocompletebox/examples/accessibility-and-internationalization/wai-aria-support/defaultcs.aspx

type "a" in the dropdown and use arrow keys to navigate through values. Do not select.

#### JAWS version and build number
JAWS 2018.1811.2ILM and 2019 latest

 
#### Operating System and version
Windows 10 Enterprise Version 1803 64 bit.

#### Browser and version:
IE 11, Edge, Firefox, Chrome. All browsers.

**Comment by JasonAment** [comment]
The aria-activedescendant is set to the ID of the text input itself and not the currently selected options.   This would explain much of the varied results that I get when testing in multiple browser and assistive technology combinations. 

<input name="ctl00$ContentPlaceholder1$RadAutoCompleteBox1" class="racInput radPreventDecorate sessioncamexclude" **id="ctl00_ContentPlaceholder1_RadAutoCompleteBox1_Input"** role="textbox" aria-busy="false" aria-disabled="false" aria-expanded="false" aria-haspopup="true" aria-readonly="false" **aria-activedescendant="ctl00_ContentPlaceholder1_RadAutoCompleteBox1_Input"** aria-owns="ctl00_ContentPlaceholder1_RadAutoCompleteBox1_listbox ctl00_ContentPlaceholder1_RadAutoCompleteBox1_tokens" accesskey="W" style="width: 10px;" aria-autocomplete="listbox" type="text" size="16" autocomplete="off">

I tested this in the following browser and Assistive Technology combinations and can verify that this is not isolated  to just JAWS.  Similar failures happen in most combinations.

- Jaws/IE11 - Reports nothing
- Jaws/Edge - Silence
- Jaws/Firefox - Reports nothing
- Jaws/Chrome - Announces as expected
- NVDA/IE11 - Reads each item twice
- NVDA/Edge - Only announces the first item. All other items are not reported.
- NVDA/Firefox - Announces the first two values over and over ("list Alejandra Camino Alexander Feuer, list Alejandra Camino Alexander Feuer")
- NVDA/Chrome - Announces as expected
- Narrator/IE11 (control is not accessible via keyboard)
- Narrator/Edge (control is not accessible via keyboard)
- Narrator/Firefox ("No value in view" or "blank")
