### ISSUE TITLE
JAWS reads "checkbox not checked partially checked" when interacting with checkbox in "mixed" state.

### ISSUE THREAD

**Issue by zelliott** [FreedomScientific/standards-support#196]
### Summary

There seems to be some kind of bad interaction when JAWS is in virtual mode within a table and focus is on a checkbox with `aria-checked="mixed"`. JAWS reads "checkbox not checked partially checked" instead of simply "checkbox partially checked". The string "not checked" is incorrect and confusing.

This bug does not repro in NVDA or Voiceover. 

### Expected result

JAWS should read "checkbox partially checked" when on a checkbox in "mixed" state.

### Actual result

JAWS reads "checkbox not checked partially checked" when on a checkbox in "mixed" state.

### Example

Codepen: https://codepen.io/anon/pen/EzooLy
Repro steps:

1. Open the Codepen and start JAWS.
2. Bring focus to the "pen region" itself (best way I found is to just click on the "pen region").
3. Ensure you are in virtual mode (insert + z).
4. Jump to the table (t)
5. Move to the second column (ctrl + alt + right arrow).

Observed: JAWS reads "checkbox not checked partially checked".
Expected: JAWS reads "checkbox partially checked".

#### JAWS version and build number

2019.1904.60 ILM Professional Edition
 
#### Operating System and version

Windows 10 Enterprise

#### Browser and version:

Chrome 74.0.3729.169

**Comment by JAWS-test** [comment]
* The problem occurs in Chrome and Firefox, not IE 11.
* The problem has nothing to do with the table or grid. It occurs with every checkbox 
```
<div aria-checked="mixed" tabindex="0" role="checkbox">2</div>
```
* In the element overview in Firefox and Chrome with INS+F5 or INS+Ctrl+X only the wrong status "not checked" is displayed.

**Comment by lamador** [comment]
The issue was reproducible in the latest version of JAWS (2020.2006.12), Chrome (83.0.4103.97), 
Firefox (77.0.1) and IE11 (11.836.18362.0) on Windows 10.  Additionally, there is a discrepancy between how the checkboxes are listed in the Select a Checkbox window (Insert + Ctrl + X) and in the Select a Form Field window (Insert + F5).  In the former, the two checkboxes are listed individually, but in the latter, the two checkboxes are erroneously identified as one checkbox.

**Comment by JAWS-test** [comment]
The problem also occurs with HTML checkboxes that have been assigned the state `indeterminate` via JS (tested with Firefox, Edge, Chrome + JAWS 2020.2008.24)

**Comment by stevefaulkner** [comment]
works in JAWS 2024.1310.70 
[test case](https://codepen.io/stevef/pen/xxMdqde)
