### ISSUE TITLE
header and footer are not output correctly

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#216]
### Summary

The html elements header and footer are not output according to the specification.

http://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_banner
http://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_contentinfo
http://www.w3.org/TR/html-aam-1.0/

Unfortunately, the specification of when to output header and footer contradicts each other, but this has no effect on the present case.

Example:
1. Save the source code as html file:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>header/footer</title>
</head>
<body>
<div id=1>
<header>The header element </header>
<main>The main element </main>
<footer>The footer element </footer>
</div>
</body>
</html>
```
2. Press Ctrl+INS+R or press R or navigate with arrow keys (reading mode)

### Expected result

The html elements header and footer are either always output or at least outside article, aside, main, nav and section.

It would also be useful if the output of html element and corresponding ARIA role were equivalent. However, this is a problem of specification and not of JAWS.

### Actual result

IE 11: No output as soon as, for example, a child element of `<div>`
Chrome: Correct.
Firefox: Is always output, even if it is a child element of `<main>` etc. 
Edge: 
* Ctrl+INS+R does not work at all
* when reading linearly `<header>` and `<footer>` are not output
* when using quick navigation with R `<header>` and `<footer>` are reached (as long as they are not inside elements such as `<main>`), but the role is not output.

#### JAWS version and build number
JAWS 2019.1904.60
To perform the test correctly, the output of landmark regions must be activated (INS+6 > Web/HTML/PDF > Reading > High). 
 
#### Operating System and version
Windows 10

#### Browser and version:
IE 11, Firefox, Chrome, Edge (always current version)

**Comment by scottaohara** [comment]
FYI @JAWS-test, if posting HTML tags inline you'll need to wrap them in ` marks, otherwise when your comment is published, GitHub will try to render those tags.

I've edited your comment to fix GitHub trying to render the markup you posted, so you can check out what i did there :)

**Comment by JAWS-test** [comment]
@scottaohara Sorry for my mistake and many thanks for the correction.

**Comment by scottaohara** [comment]
no worries at all :)

**Comment by scottaohara** [comment]
Back to the issue at hand...

can confirm that markup structure has an impact on how landmarks are exposed / discoverable by JAWS, with the greatest variability being with IE11 (which makes sense due to it's lack of native support for the landmark roles).

Test cases:
* [header, main and footer elements as direct children of body](https://scottaohara.github.io/tests/html-landmarks/header-footer-main-no-div.html)
* [header, main and footer elements as children of a DIV with ID](https://scottaohara.github.io/tests/html-landmarks/header-footer-main.html )

**Comment by scottaohara** [comment]
Additional tests for `header` and `footer`:

* [header element scoping tests/results](https://scottaohara.github.io/tests/html-header/banner-landmark-tests.html)
* [footer element scoping tests/results](https://scottaohara.github.io/tests/html-footer/contentinfo-landmark-tests.html)
