### ISSUE TITLE
input with datalist does not work

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#218]
### Summary

input with datalist does not work

1. Save the source code as html
```html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>datalist</title>
	</head>
	<body>
		<label for='combo'>Browser</label>
		<input type='text' id='combo' list='browser' >
		<datalist id='browser'>
			<option value='Firefox'>
			<option value='Chrome'>
			<option value='Internet Explorer'>Version 11
			<option value='Edge'>
			<option value='Safari'>
			<option value='Opera'>
		</datalist>
		And now something completely different....
	</body>
</html>
```
2. tab to the combo box, read with arrow keys, navigate with E and C and look at the entries in the element lists (CRTL+INS+C, CTRL+INS+E)

### Expected result

1. input fields with datalist are output with a separate role (distinguishable from input fields and select elements, although the specification unfortunately defines the same role for some select elements and combo boxes, which is an error)
2. label for is output correctly
3. automatic fade in of list entries during text input is notified (similar to input fields with autocomplete function)
4. you can navigate through the list entries
5. the list entries are output correctly

### Actual result

No browser meets all requirements.

The only pleasing thing is that in Chrome and Edge (Chromium) the specification is violated and select and input datalist are output with different roles. Although the output of the roles is confusing (role=combobox is output as "edit combo" and select is output as "combobox"), the output itself is correct. I also think it makes sense that the combo boxes can be reached with both C and E (only in Chrome and future Edge).

* Internet Explorer: Output as input field ("edit"), no output of list entries, instead of the label the text  behind the field is output
* Chrome and Edge (Chromium): 
	* positive: output as "edit combo" (and thus distinguishable from select, which is output as "combobox"), quick navigation and element overview with C and E possible
	* negative: the list entries are output as menu (which is wrong because they are listbox), the first letter is output as accesskey (is unnecessary), the fade in of list entries is not noticeable, if there is text content in addition to the value, this is output twice.
* Firefox: Is only output as an input field ("edit"), the text behind it is output several times as a label, output of "has popup", the fade in of the list entries is not noticeable, navigation through list entries is not possible (since change from form mode to linear reading mode), therefore no elements selectable, in application mode (role=application): no output of the list entries
* Firefox ESR: same as with Firefox, but in application mode the list entries are output twice	
* Edge: output as "combo box" with tab navigation and in the element list (INS+F5), "combo edit" when linear reading, label and text behind it is output as label, fade in of list entries not perceptible, list entries not perceptible during arrow key navigation in the list

The incorrect output is problematic because the ARIA combobox role is not output correctly at least in Edge and IE 11, so that there is no possibility for the two Microsoft browsers to implement combo boxes. Combo boxes are very common on the web and most frameworks use them instead of select elements.

### Example

see above

#### JAWS version and build number

JAWS 2019.1906.10
The problems occur analogously with older versions of JAWS (JAWS 15, 16, 17, 18, 2018).
 
#### Operating System and version

Windows 10, Windows 8

#### Browser and version:

Internet Explorer 11.0.9600.19400
Chrome 75.0.3770.100
Edge  41.16299.1004.0
Edge 77.0.211.3 (Chromium)
Firefox 68.0
Firefox ESR 60.8.0

**Comment by stevefaulkner** [comment]
@JAWS-test I tested ([test case](https://codepen.io/stevef/pen/QWYOYNK)) this with latest JAWS 2024 and latest browsers, worked as expected for me.
