### ISSUE TITLE
Slider - JAWS narrates slider value twice when using PageUp / PageDown

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/standards-support#220]
Repro steps:
1. Go to https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-2.html. 
2. Switch off virtual cursor
3. Navigate into vertical slider "Temperature"
4. use Page Up/Page down keys to change value
Expected result
JAWS narrates new value on the slider

Actual result
JAWS narrate new value twice

Example
https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-2.html

Additional Information
Reproducible with Chrome and Firefox. Other browsers haven't tested.

JAWS version and build number
2019.1906.10

Operating System and version
Windows 10 Enterprise
version: 1903

Browser and version:
Chrome
Version 75.0.3770.100 (Official Build) (64-bit)

Firefox
68.0 (64-bit)

**Comment by stevefaulkner** [comment]
Tested with JAWS 2024.2310.70 and Chrome 119. Works as expected - [test case](https://cdpn.io/pen/debug/oNmpoYg)
