### ISSUE TITLE
 input type=file is not output correctly

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#224]
### Summary

input type=file is not output correctly

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>input type=file</title>
	</head>
<body>
	Without label: <input type=file><hr>
	With label for: <label>passport photo <input type=file></label><hr>
	With aria-label: <input type=file aria-label="passport photo">
</body>
</html>
```
2. tab to the input type=file, read with arrow keys, navigate with E and B and look at the entries in the element lists (CRTL+INS+B, CTRL+INS+E, INS+F5)
3. choose a file for upload and repeat step 2

### Expected result

1. label is output
2. type (file upload) will be output
3. status (file selected or not) and file name for selected file is output
4. consistent output in different browsers

#### Firefox
* label for: Label is not output (independent of navigation method)
* aria-label: Label is only output for forward tab navigation, but not for quick navigation with B or backward tab navigation (Shift+tab) and not in the element list
* aria-label: Status is not perceptible (file name or reference to non-selected file is not output)

#### Chrome
* with label: Button type not perceptible (only output as button, no reference to file upload)
* with and without label: Status is not perceptible (file name or reference to non-selected file is not output)

#### IE 11
two elements during tab navigation:
* input field: change to form mode, output of "file upload edit" and operating instruction (This is misleading, as no text input is possible here. A read-only input field would be useful)
* button: "file upload edit Browse ..." (That's misleading because it's a button, not an input field. Sometimes the button is also correctly output as a button. However, no regularity could be determined, after which sometimes this and sometimes that output occurs.)

If the focus is in the input field and you read with the arrow keys, the element is not output at all, there are only 3 empty steps

#### JAWS version and build number

JAWS 2019.1906.10
 
#### Operating System and version

Windows 8

#### Browser and version:

Internet Explorer 11.0.9600.19400
Chrome 75.0.3770.100
Firefox 68.0

**Comment by kurtjwolf** [comment]
Similar issues with type="file" filed internally as bug #104896. Added link to this reported issue.

**Comment by jgauvreau** [comment]
Is it possible to get a status update on this issue? I see that @kurtjwolf confirmed this as a valid issue and reported that other similar issues with JAWS announcing changes to <input type="file" /> elements were already filed internally at VFO under bug #104896. Is there an estimated timeline for when a fix will be implemented in JAWS 2021?

**Comment by stevefaulkner** [comment]
tested with JAWS 2024.2310.70 and Chrome Version 119.0.6045.124 (Official Build) (64-bit) and Firefox 119.0.1 (64-bit) using test case https://codepen.io/stevef/pen/gOqXjPm

JAWS announced what was exposed in the acc tree as expected. There is a difference between output from chrome and Firefox as the input is exposed differently by each browser.

@JAWS-test Closing this as fixed as I see only possible browser bugs :-)
