### ISSUE TITLE
Value and role are not displayed with INS+CTRL+C

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#225]
### Summary

Value and role are not displayed with INS+CTRL+C and display does not match with INS+F5 and output with tab navigation.

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Ctrl+Ins+C</title>
	</head>
<body>
	<select aria-label=select><option>1</select>
	<select size=2 aria-label=select_size><option selected>2<option>3</select>
	<select multiple size=3 aria-label=select_multiple><option selected>4<option selected>5<option>6</select>
	<input list=cb value=7 aria-label=datalist><datalist id=cb><option>7a<option>7b</datalist>
	<div role=tablist aria-label=tab><div role=tab tabindex=0 aria-selected=true>8</div><div role=tab tabindex=-1 aria-selected=false>9</div></div>
	<div role=tree aria-label=tree><div role=treeitem tabindex=0 aria-selected=true>10</div><div role=treeitem tabindex=-1 aria-selected=false>11</div></div>
	<div role=listbox aria-label=listbox><div role=option tabindex=0 aria-selected=true>12</div><div role=option tabindex=-1 aria-selected=false>13</div></div>
	<div tabindex=0 role=button aria-haspopup="listbox" aria-label="listbox">14</div>
	<div role="combobox" aria-expanded="false" aria-haspopup="listbox" aria-label=combobox1><input type="text" aria-autocomplete="list" aria-label=combobox2 value=15></div>
</body>
</html>
```
2. press INS+CTRL+C
3. Compare the output with INS+F5 and tab navigation

### Expected result

* Because INS+CTRL+C display elements with different roles (tree, tab, listbox, multiple listbox, combobox, drop-down), the role should be displayed in the element list.
* The value and the label are displayed.
* The output is the same as for INF+F5.
* The output is the same as for tab navigation.
* consistent output in different browsers

### Actual result

* The role is never displayed.
* The value is never output if there is a label.
* If there is no label, the value is partially output (to test the elements the aria-label must be removed)
* Different output for INS+F5
* Different output for tab navigation
* Different output depending on browser

Examples:
* Edge, Chrome at combobox: Display of the outer label (at role=combobox) in element list, with tab output of the inner label (at the input element) 
* IE 11: role=combobox is output as unlabelled (INS+F5)
* Firefox: role=combobox with INS+CTRL+C only display of value, with INS+F5 only display of label
* INS+F5: button with aria-haspopup=listbox as button, but also display at INS+CTRL+C and thus indirectly as listbox
* Firefox, Edge and Chrome: at INS+F5 display of some elements with wrong information "checked not checked sub men" (e.g. at tree and listbox, cause is the implicit aria-orientation)
* INS+F5: value is displayed for few elements (select size=1, datalist) if there is a label 
* HTML-combo edit with datalist element are not displayed in Firefox and IE 11 with INS+CTRL+C
* Incorrect output of the role of combo edit with datalist and partly with role=combobox in Firefox and IE 11 (INS+F5, tab navigation), see: https://github.com/FreedomScientific/VFO-standards-support/issues/221 and https://github.com/FreedomScientific/VFO-standards-support/issues/218

#### JAWS version and build number

JAWS 2019.1906.10
 
#### Operating System and version

Windows 8

#### Browser and version:

Internet Explorer 11.0.9600.19400
Chrome 75.0.3770.100
Firefox 68.0
Edge 77.0.211.3 (Chromium)

**Comment by stevefaulkner** [comment]
@JAWS-test closing as it is up to freedom scientific what they choose to display in different features
