### ISSUE TITLE
JAWs incorrectly announces combobox input depending on how it is tabbed to

### ISSUE THREAD

**Issue by NickColley** [FreedomScientific/standards-support#228]
### Summary

User feedback:

> When using JAWS, I navigated with the ‘Tab’ key and located a link which announced as ‘Search design system’. I selected the link and was taken directly to an autocomplete to search for a component.

Video demonstration in context on the Design System website: https://youtu.be/CFvk9W5hE0o

I've managed to reproduce this issue in Internet Explorer 11 and using JAWS 2018, it seems to be a bug with JAWS where the link's announcement is duplicated onto the input's announcement.

Tab to Design System home link
Announcement: "GOV.UK Design System link"
Tab to 'Search design system' input
Announcement: "Search design system visited link"
Shift tab to Design System home link
Announcement: "GOV.UK Design System link"
Tab to 'Search design system' input
Announcement: "Search design system edit combo [...]"

This does not happen when tabbing away from the input and tabbing back towards in the input.

When removing the `[role=combobox]` wrapper, the problem no longer exists.

### Expected result

When tabbing to the input it is announced correctly.

### Actual result

When tabbing to the input it is announced as the previous announcement, in this case it is announced as the previous link.

### Example

Minimal markup to reproduce the issue:

```html
<a href="/">Home</a>
<label for="username">Username</label>
<div role="combobox">
  <input id="username">
</div>
```

JS Bin live example: https://output.jsbin.com/yafiwuk

#### JAWS version and build number

JAWs 2018
 
#### Operating System and version

Windows 10

#### Browser and version:

Internet Explorer 11

**Comment by JAWS-test** [comment]
see https://github.com/FreedomScientific/VFO-standards-support/issues/221

**Comment by nickcolley** [comment]
Just for some more context, we have moved our component back to the ARIA 1.0 specification for combobox and it has resolved this problem, so I think JAWs should look to support both ARIA 1.0 and ARIA 1.1 patterns for combobox for the future.

**Comment by JAWS-test** [comment]
> Just for some more context, we have moved our component back to the ARIA 1.0 specification for combobox and it has resolved this problem, so I think JAWs should look to support both ARIA 1.0 and ARIA 1.1 patterns for combobox for the future.

I'm very surprised to read this, because even the ARIA 1.0 pattern doesn't work with IE 11 and JAWS (no matter which version). As an example http://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html can be used, but I also tried many other variants. Can you send me an example (source code or URL) that works for you?

**Comment by nickcolley** [comment]
Sure thing, here is an example of our component where we've reverted the newer ARIA 1.1 pattern:

https://alphagov.github.io/accessible-autocomplete/examples/form-single.html

**Comment by JAWS-test** [comment]
Thank you for the example. But this is more an input field with autocomplete function than a combined input field. It works perfectly as an input field (mainly thanks to various input hints). However, it does not work as a combined input field. For example, the combobox role of JAWS with IE 11 is not output.
In Chrome, on the other hand, the input instructions contradict each other. With Chrome, JAWS recognizes the field as a combobox and therefore outputs a message that list entries can be selected with the arrow keys. However, this is not possible without previous text input here.
Therefore I would recommend to simply remove role=combobox. Then it works well in all browsers and corresponds more to the actual implementation.

**Comment by stevefaulkner** [comment]
Closing this as it appears to be an IE 11/JAWS bug and we are no longer supporting IE 11
