### ISSUE TITLE
JAWS grouping labels truncating text to 256 characters in all browsers

### ISSUE THREAD

**Issue by KreinerM2** [FreedomScientific/standards-support#229]
### Summary
The below scenarios where tested in all three major browsers including Chrome, Firefox, and Internet Explorer and each gave the same result when tabbing into the radio button questions in forms mode for both JAW 18 and 19.

Please see https://www.w3.org/WAI/tutorials/forms/grouping/ for more information on the recommended practices on grouping form elements. 

### Expected result
It is expected that all of the text within the grouping label would read both in the browser UI and within the JAWS dialog. 

### Actual result
The JAWS dialog always cuts off reading at 256 characters. The first two examples in CodePen cut off at 256 characters in the browsers UI as well. Whereas the third example reads the whole grouping label within the browser UI, but still cuts off at 256 characters within the JAWS dialog. 

**NOTE: Tested with text boxes as well. It would appear that all associated labels to form elements will always cut off at 256 characters within the JAWS dialog. 

### Example
https://codepen.io/KreinerM2/pen/GVmzGq

#### JAWS version and build number
Tested with: 
 2018.1811.30 and 2019.1810.64. Outcomes were identical 

#### Operating System and version
Microsoft Windows 10.0.17763

#### Browser and version:
Tested with:
Chrome 75.0.3770.142
Firefox Quantum 68.0.1
Internet Explorer 11.557.17763.0

**Comment by LauraOH** [comment]
Note I'm having an issue with Jaws 2018 and Edge where the aria-labelledby on the group is not being read.

**Comment by JAWS-test** [comment]
The limitation probably results from the fact that the group label is output before the item label (and with IE for every element within the group). While researching on the internet, I found only hints that the group label should be short and meaningful, but I did not find a page that specifies a maximum length for the legend element or the group role.
So I think it makes sense to limit it to a certain number of characters, but it should be defined in the HTML and ARIA specification and in "Accessible Name and Description Computation".

**Comment by menovak** [comment]
8/8/2019 update (Per Kurt's notes):

Across multiple browsers, JAWS truncates fieldset legends and ARIA group names (role="group" and role="radiogroup") in Virtual Cursor Mode and Forms Mode.  

JAWS reads only the first 253 characters of a legend in Chrome and Firefox, but reads all characters from legend in IE 11. NVDA does not have this issue and reads all characters.

JAWS reads only the first 253 characters of the name assigned by aria-labelledby to a role="group" or role="radiogroup" in IE 11, Chrome, and Firefox. NVDA does not have this issue and reads all characters. Of note, character limits do not affect JAWS and aria-labelledby without these roles.

Important Note: Fieldset legends and ARIA groups should be the primary way to relate question text to form element answers in all web applications, except for this flaw.

Note:  Bugzilla #110336  has been filed

**Comment by stevefaulkner** [comment]
@BenKeyFSI can you post an update on whats happening with this  Bugzilla #110336 internal bug? We have a client that is effected by this issue.

**Comment by BenKeyFSI** [comment]
@stevefaulkner According to BugZilla, this bug was fixed in JAWS 2020.1911.65 and the fix was verified by test.

**Comment by stevefaulkner** [comment]
@BenKeyFSI thats good, will check and verify

**Comment by stevefaulkner** [comment]
tested with JAWS 2024 AND CHROME 119. works as expected.
