### ISSUE TITLE
No change from application mode with article (IE, Firefox)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#234]
### Summary

No change from application mode with article

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>application / article</title>
	</head>
	<body>
		<div role='application'>
			<div role=document tabindex=0>
				role=document
			</div>	
			role=application
			<div role=article tabindex=0>
				role=article
			</div>	
			<a href="https://www.w3.org/TR/wai-aria-1.2/#application">role=application</a>
			<div role=article>
				<a href="http://www.w3.org/TR/wai-aria-1.2/#article">role=article</a>
			</div>	
			<div role=document>
				<a href="https://www.w3.org/TR/wai-aria-1.2/#document">role=document</a>
			</div>
	         </div>
	</body>
</html>
```
2. Navigate with Tab key to article
3. Try to read the page content with arrow keys

### Expected result

According to the specification it should be possible to leaf the application mode and read with the arrow keys when focusing role=article/document or an element inside it 
https://www.w3.org/TR/wai-aria-1.2/#article
https://www.w3.org/TR/wai-aria-1.2/#application 

### Actual result

It works well with role=document, but in IE und Firefox not with role=article

IE 11: JAWS remains in application mode at role=article
Chrome: Ok (JAWS switches to reading mode)
Firefox ESR: JAWS switches to reading mode only when the role=article gets the focus, but not when an element within the role=article gets the focus.

The wrong behavior occurs regardless of whether role=article or the HTML element article is used.

#### JAWS version and build number

JAWS 2019.1906.10
 
#### Operating System and version

Windows 10

#### Browser and version:

Internet Explorer 11.1268.16299.0
Chrome 76.0.3809.100
Firefox 60.8.0 ESR

**Comment by stevefaulkner** [comment]
tested with JAWS 2024 and  Firefox 120, works as expected 
[test case](https://cdpn.io/pen/debug/MWLXNxP)
