### ISSUE TITLE
links with special characters before and after are not output correctly

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#239]
### Summary

links with special characters before and after are not output correctly

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>links</title>
	</head>
	<body>
		[<a href="#">1</a>]
		(<a href="#">2</a>)
		{<a href="#">3</a>}
		&lt;<a href="#">4</a>&gt;
		<hr>
		<h2>For comparison: correct output</h2>
		1<a href="#">0</a>1
		l<a href="#">i</a>nk
	</body>
</html>
```
2. Navigate with arrow keys and quick navigation (u)
3. check the link overview (INS+F7)

### Expected result

Correct output of all links (with reading pause before and after the link)

### Actual result 

* Chrome, IE 11: link overwiew (INS+F7): "[1" instead of "1" (opening bracket outside the link is output)
* Firefox ESR, Chrome, IE 11: reading with arrow keys and quick navigation (u): link + following closing bracket is output (without reading pause), using the [] brackets also the opening bracket is output. 

#### Note

* The problem occurs not only with brackets, but also with other special characters (e.g. ").
* The problem also occurs with older versions of JAWS.

#### JAWS version and build number

JAWS 2019.1906.10
 
#### Operating System and version

Windows 10

#### Browser and version:

Internet Explorer 11.0.9600.19400
Chrome 75.0.3770.100
Firefox 60.8.0 ESR

**Comment by lamador** [comment]
The issue with special characters being included with the link name was reproduced in IE11 11.1016.18362.0, Chrome 85.0.4183.83, and Firefox 80.0.1, using JAWS 2020.2008.24 on Windows 10 when navigating using the virtual PC cursor and the {{U}} shortcut key.  

The link names are don't include special characters in the list of links window opened activated using the {{Insert + F7}} key. Link names are also properly annouced when navigating using the {{Tab}} key.

**Comment by stevefaulkner** [comment]
Tested with JAWS 2024 and Chrome 119 using [test case](https://codepen.io/stevef/pen/wvNxmdZ). Works as expected
