### ISSUE TITLE
JAWS reads "has flows from" after each element in Electron pane

### ISSUE THREAD

**Issue by RussellSprouts** [FreedomScientific/standards-support#242]
### Summary

VSCode extensions and other features can host HTML content in a tab in the Electron app.
However, JAWS will read "has flows from" after each element, even when there are no `aria-flowsfrom` attributes. The same HTML will work fine in Chrome.

### Expected result
JAWS should read the webview content the same as in a browser.

### Minimal repro

I have created a repo with a minimal VSCode extension to demonstrate the issue. The extension provides a command to show a webview with some sample content.

See https://github.com/RussellSprouts/vscode-a11y-bugs-demo

#### JAWS version and build number
JAWS 2019.1907.42

#### Operating System and version
Version	10.0.18362 Build 18362

#### Browser and version:
Tested with:
VSCode 1.37.1
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0

VSCode 1.38.0-insider (user setup)
- Electron 4.2.9
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0

**Comment by RussellSprouts** [comment]
See also: https://github.com/microsoft/vscode/issues/79250

**Comment by stevefaulkner** [comment]
closing here as is being dealt with elsewhere
