### ISSUE TITLE
JAWS 2019.1907.42 not narrating the position for listitem and menuitem (JAWS+Chrome)

### ISSUE THREAD

**Issue by devandqatools** [FreedomScientific/standards-support#252]
### Summary

 1. Open Chrome Browser.
 2.. Go to https://jsfiddle.net/chidvilash513/702hrtku/21/ 
 3. Enable JAWS and traverse the page in scan mode.
 4. Navigate to display control and verify the screen reader behavior, whether it is narrating the position set of individual elements.

Expected result:
When screen reader focus land on the "Display" control, JAWS should narrate the position of the control along with name and role.

**Comment by scottaohara** [comment]
Hi @devandqatools 

There appear to be some issues with your pattern that should be rectified to properly test.
e.g. links are not valid children of `menuitem`, and the `menuitem`s within the `menu` should be the focusable elements.

Please review: http://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html

if you are still having additional issues after updating your pattern, please let us know.

**Comment by JAWS-test** [comment]
Incorrect implementation results in the list entries not being reached with the arrow keys because JAWS is not in form mode or application mode. After deactivating the reading mode, the menu can be operated with the keyboard, but the position is not output, which is also due to incorrect marking.
