### ISSUE TITLE
aria-labelledby is not output with highest priority (IE 11)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#254]
### Summary

aria-labelledby is not output with highest priority (IE 11)

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>aria-labelledby</title>
	</head>
	<body>
		<a href=#  aria-labelledby="1">content</a>
		<span id=1>aria-labelledby</span>
	</body>
</html>
```
2. Navigate with Tab key, U and arrow keys, INS+F7

### Expected result

aria-labelledby is output with highest priority according to https://w3c.github.io/accname/#mapping_additional_nd_name

### Actual result 

* Tab navigation: aria-labelledby is output as label
* U, INS+F7, reading with arrow keys: content is output as label
* Only in IE 11
* In contrast to older JAWS versions, the output of labels in IE 11 has improved significantly in recent years, but there are still a few inconsistencies in the priority of labeling methods

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 10

#### Browser and version:

Internet Explorer 11.1268.16299.0

**Comment by stevefaulkner** [comment]
closing as wontfix IE only issue
