### ISSUE TITLE
explicit and implicit role=presentation is not interpreted correctly

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#256]
### Summary

explicit and implicit role=presentation is not interpreted correctly

1. Save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>role=presentation</title>
	</head>
	<body>
		<h1>Rule 1: role="presentation" is ignored due to the global ARIA property</h1>
		<h2 role="presentation" aria-haspopup="true"> Rule 1 </h2>
		<input role="presentation" disabled value=123 aria-label="Rule 1">

		<h1>Rule 2: role="presentation" is not ignored with non-global ARIA property</h1>
		<h2 role="presentation" aria-level="2"> Rule 2 </h2>
		<input role="presentation" disabled value=123  aria-multiline="true" title="Rule 2">

		<h1>Rule 3: role="presentation" is ignored because focusable</h1>
		<h2 role="presentation" tabindex=0> Rule 3 </h2>
		<input role="presentation" title="Rule 3" value=123>

		<h1>Rule 4: role="presentation" is ignored because explicit role</h1>
		<table role=presentation>
			<tr role=link><th>Rule<th>4a</tr>
			<tr><td>Rule<td>4b</tr>
		</table>	
		<ul role=presentation>
			<li role=button>Rule 4a</li>
			<li>Rule 4b</li>
		</ul>

		<h1>Rule 5: implicit role="presentation"</h1>
		<button><h2>Rule 5a</h2></button>
		<div role=button><input title="Rule 5a" disabled value=123>Rule 5a</div>
		
		<div role=img aria-label="image"><h2>Rule 5b</h2></div>
		<div role=img aria-label="image"><input title="Rule 5b" disabled value=123></div>

		<div role=checkbox aria-checked=false><h2>Rule 5c</h2></div>
		<div role=checkbox aria-checked=false><input title="Rule 5c" disabled value=123>Rule 5c</div>

		<div role=separator><h2>Rule 5d</h2></div>
		<div role=separator><input title="Rule 5d" disabled value=123></div>
		
		<h1>Rule 6: role="presentation" without one of the exceptions</h1>
		<h2 role="presentation">Rule 6</h2>
		<input role="presentation" disabled value=123 title="Rule 6">
	</body>
</html>
```
2. read with arrow key or use element lists (INS+F5, INS+F6, INS+F7)

### Expected result

correct output according to https://www.w3.org/TR/wai-aria-1.2/#presentation

### Actual result

* Partially incorrect output
* Inconsistent output: depending on browser or with implicit role=presentation depending on ARIA role
* Different output of the value in the input field (I did not document this further, because it appears to me as a secondary problem)

The following are the test results (in the order Chrome / Firefox)

#### Rule 1: 
* h2: false / false
* input: false / false

#### Rule 2: 
* h2: ok / ok
* input:  ok / ok

#### Rule 3:
* h2: ok / ok
* input: ok / ok

#### Rule 4:
* link: ok / ok
* button: ok / ok

#### Rule 5:
* button
	* h2: o ok / ok
	*input: ok / ok
* image
	* h2:  ok / false
	* input:  ok / false
* checkbox
	* h2: ok / ok
	* input:  ok / ok
* separator
	* h2:  ok / no output at all without label, ok with label
	* input:  ok / no output at all without label, ok with label

#### Rule 6:
* h2:  ok / ok
* input:  ok / ok

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2

**Comment by stevefaulkner** [comment]
removed IE results from https://github.com/FreedomScientific/standards-support/issues/256#issue-484762317

from review using latest chrome and firefox, JAWS respects output as per accessibility tree
[test case](https://cdpn.io/pen/debug/oNVwjag)

**Comment by JAWS-test** [comment]
@stevefaulkner 

> JAWS respects output as per accessibility tree

I see it differently: with Rule 5, Chrome always transmits the child elements to the API, but only with the button does JAWS decide to output the heading as a heading, while NVDA does it with the button and checkbox. Perhaps there are good reasons to deviate from the ARIA specification here and ignore implicit role=none for certain roles, but then a ticket should be opened in the ARIA specification with a corresponding justification
