### ISSUE TITLE
After certain elements, headings are not output with the virtual cursor (Chrome, Firefox)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#260]
### Summary

heading is not output

1. Save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>h2</title>
	</head>
	<body>
	
		<article>
			<p>paragraph</p>
		</article>
		<figure>
			<img src="#" alt="">
		</figure>

		<h2>heading</h2>

		<article>
			<p>paragraph</p>
		</article>
	
	</body>
</html>
```
2. Read with arrow keys

### Expected result

h2 is output as heading

### Actual result

* h2 is not output as heading
* Problem occurs only in Chrome and Firefox; not in IE 11
* Problem occurs only if these elements are exactly in front of the heading. If an element is removed, the output is correct.
* The problem only occurs when reading with the arrow keys.
* The source code is bizarre, but unfortunately the problem occurs with one of my customers like this

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8
Windows 10

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by stevefaulkner** [comment]
could not reproduce with JAWS 2024 and latest chome/firefox
[test case](https://codepen.io/stevef/pen/LYaLGNN)
