### ISSUE TITLE
Removing display:none does not always result in Live Region output (IE 11)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#267]
### Summary

Removing display:none does not always result in Live Region output (IE 11)

1. Save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>live region</title>
		<style id=2>
			.none {display:none;}
		</style>
	</head>
	<body>
		<div id=1 class=none aria-live=assertive>
			live region
		</div>
		<button onClick="document.getElementById('1').removeAttribute('class');">remove class</button>
		<button onClick="document.getElementById('1').setAttribute('class','test');">change class</button>
		<button onClick="document.getElementById('1').setAttribute('style','display:block;');">add style attribute</button>
		<button onClick="document.getElementById('2').innerHTML='';">remove style element</button>
		<button onClick="document.getElementById('2').innerHTML='.none {display:block;}';">change style element</button>
	</body>
</html>
```
2. Activate all buttons one after the other. The page must be reloaded after each button.

### Expected result
Removing display:none always results in the output of the live region.

### Actual result
* With three methods (buttons "add style attribute", "remove style element", "change style element") there is no output of the live region in IE 11
* If aria-live is replaced by role=alert, there is no output at all in IE 11 (independent of the method)
* Works in Chrome and Firefox

See also https://github.com/w3c/aria-practices/issues/78 and many other problems with live regions: https://github.com/FreedomScientific/VFO-standards-support/issues?q=live+region

Note: In Chrome, the output only occurs if the visibility is changed for a descendant element of the Live region, in IE 11 only if it occurs directly at the Live region. Therefore the example for Chrome should look like this:
```
<div aria-live=assertive>
	<div id=1 class=none>
		live region
	</div>
</div>	
```
For it to work in Chrome and IE 11, the Live Region must be inserted twice:
```
<div aria-live=assertive>
	<div id=1 class=none aria-live=assertive>
		live region
	</div>
</div>	
```
In Chrome, however, it works if the Live region is faded in and not a child element, if the Live region is marked with role=alert. 

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by stevefaulkner** [comment]
IE 11 issue closing as wontfix
