### ISSUE TITLE
autocomplete and aria-autocomplete are not output

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#278]
### Summary

autocomplete and aria-autocomplete are not output

1. Save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>autocomplete</title>
	</head>
	<body>
		<h2>ARIA</h2>
		<input aria-autocomplete=list>	
		<input aria-autocomplete=inline>	
		<input aria-autocomplete=both>
		<h2>HTML</h2>
		<input autocomplete=on>
		<input autocomplete=off>
		<input autocomplete=username>
	</body>
</html> 
```
2. Navigate with Tab key to the input fields

### Expected result
* output of the autocomplete function
* output of the type of autocomplete function

### Actual result
* Chrome, IE 11: no output to autocomplete function
* Firefox: only aria-autocomplete=list and aria-autcomplete=both are output as aria-haspopup=true; the others are not output either 

Note: NVDA outputs the fields with the reference to Autocomplete function (without telling the type). This works with Firefox in all cases, in Chrome only with aria-autocomplete and in IE 11 not at all.

#### JAWS version and build number

JAWS 2019.1907.42
NVDA 2019
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by JAWS-test** [comment]
See also: https://github.com/w3c/aria-practices/issues/1134

**Comment by stevefaulkner** [comment]
@JAWS-test Closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).

**Comment by JAWS-test** [comment]
@stevefaulkner Tested with current Chrome and JAWS 2024: The problem still exists. I would expect that at least like NVDA the aria-autocomplete is output by JAWS because it is relevant information.
