### ISSUE TITLE
Treeview support

### ISSUE THREAD

**Issue by bart-simons** [FreedomScientific/standards-support#292]
### Summary

How to work with a tree view in IE11?
Example: http://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html

When reading the page with the arrow keys, JAWS announces the tree view (without activating forms/application mode). 

In Chrome, hitting Enter opens the tree view and lets you move through it by the arrow keys. JAWS feedback is spoken in the correct language and shown in braille.

In IE11 nothing really happens after hitting enter on the tree view. I hear the forms mode "popping sound" but no braille and nothing happens when moving by arrow keys.
The results are somewhat better when landing on the tree view by tabbing to it. Then I can move with arrow keys but nothing is shown in braille, the spoken feedback is not as precise as in Chrome (which nodes are expanded? how many siblings? etc) and everything is spoken in the JAWS default language (in my case Dutch) instead of English as indicated by the lang attribute in the HTML element.

### Expected result

Better support for treeviews in IE11
Similar experience as in Chrome.
I also expect that I open the tree view when I hit enter on it. It is not common practice to tab to such a control.

### Actual result

See above, no good support for navigating treeviews in IE11.

### Example

http://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html
http://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2b.html

### Additional Information

JAWS version 2019.1907.31
Windows 10
IE11 and Chrome 76 (64 bit)

**Comment by JAWS-test** [comment]
> When reading the page with the arrow keys, JAWS announces the tree view (without activating forms/application mode).

That's correct, and anything else would be wrong. Automatic change in form mode when reading with arrow keys is only possible with input fields

> In IE11 nothing really happens after hitting enter on the tree view

This is a long-standing error  in JAWS. I also find it problematic that the selected entry is not perceptible when reading with the arrow keys

> The results are somewhat better when landing on the tree view by tabbing to it

With Tab, the following output for the arrow key navigation in form mode is almost correct for me. I only hear "empty" before each entry.

> which nodes are expanded?

I also hear this with IE 11

> everything is spoken in the JAWS default language

This is a standard problem of JAWS and exists with many elements. But it is also a problem of the specification: https://github.com/w3c/accname/issues/56
