### ISSUE TITLE
SVG graphics are not output correctly

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#304]
### Summary

SVG graphics are not output correctly

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>SVG</title>
		<style>svg  {background-color:yellow;width:240px;height:80px;}</style>
	</head>
	<body>
			<h2>1: empty</h2>
			<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
			</svg>	

			<h2>2: with text</h2>
			<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
				<text x="40" y="35">text2</text>
			</svg>	

			<h2>3: with title</h2>
			<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
				<title>title3</title>
			</svg>	

			<h2>4: with title and desc</h2>
			<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
				<title>title4</title>
				<desc>description4</desc>
			</svg>	

			<h2>5: with title, desc and text</h2>
			<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
				<title>title5</title>
				<desc>description5</desc>
				<text x="40" y="35">text5</text>
			</svg>	

			<h2>6: with title and aria-labelledby</h2>
			<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg" aria-labelledby=1>
				<title id=1>title6</title>
			</svg>	

			<h2>7: with title and aria-labelledby, desc and aria-describedby</h2>
			<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg" aria-labelledby=2 aria-describedby=3>
				<title id=2>title7</title>
				<desc id=3>description7</desc>
			</svg>	

			<h2>8: with text, title and aria-labelledby</h2>
			<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg" aria-labelledby=4>
				<title id=4>title8</title>
				<text x="40" y="35">text8</text>
			</svg>	
		</body>	
</html> 
```
2. read with arrow keys
3. navigate with G
4. press INS+Ctrl+G

### Expected result
* without role=img or with role=document/application not as graphic
* with role=img as graphic
* consistent output of title, description, text content according to https://www.w3.org/TR/svg-aam-1.0/#mapping_additional_nd (for SVG without role=img) and according to https://www.w3.org/TR/accname-1.1/ (for SVG with role=img or with role=document/application)

#### IE
* INS+Ctrl+G, G: no graphics
* reading: 7 graphics (example 2-8): title, desc and text content (each as a single graphic)

#### Chrome 
* INS+Ctrl+G: 6 graphics (example 3-8, only title)
* reading, G: If title and text content exist, only the text content is output
* G: 6 graphics (example 3-8, text content or title, as when reading)
* reading: 7 graphics (example 2-8)
	* 2: text content
	* 3: title
	* 4: title
	* 5: text content
	* 6: title
	* 7: title (and operating instruction for aria-describedby)
	* 8: text content

#### Firefox 
* INS+Ctrl+G, G, reading: no graphics
* reading: title and text content are output as text without a role. If title and text content exist, only the text content is output.

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by JAWS-test** [comment]
If role=img is added to the svg element, the following output is made:

#### IE 11
Same output as without role=img

#### Chrome 
Same output as without role=img except:
* example 1: output as unlabelled graphic
* exmaple 2: no output

#### Firefox
INS+Ctrl+G, G, reading: 
* example 1 and 2 (without title): no output
* example 3 - 8: output of title and role "graphic", no output of text content and desc

**Comment by stevefaulkner** [comment]
@JAWS-test Closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).
