### ISSUE TITLE
 labels are not output consistently

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#305]
### Summary

labels are not output consistently

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>AccName</title>
	</head>
	<body>
		
		<h2>label for</h2>
		<label for=1>1</label>
		<label for=2>2</label>
		<hr>
		<select id=1><option>a<option>b</select>
		<input type=checkbox id=2>

		<h2>label</h2>
		<label><select><option>a<option>b</select>3</label>
		<label>4<input type=checkbox></label>

		<h2>aria-label</h2>
		<select aria-label=5><option>a<option>b</select>
		<input type=checkbox aria-label=6>
		
		<h2>aria-labelledby</h2>
		<span id=7>7</span><span id=8>8</span>
		<hr>
		<select aria-labelledby=7><option>a<option>b</select>
		<input type=checkbox aria-labelledby=8>

		<h2>title</h2>
		<select title=9><option>a<option>b</select>
		<input type=checkbox title=10>
	</body>
</html>
```
2. read with arrow keys

### Expected result
* consistent output of the labels at the form field, independent of the form field type and independent of the label type.
* consistent output of the labels, if they are not directly next to the element
* Consistent output between different browsers

### Actual result 
* Output of label depends on form field type and labeling method
* if label is not at the element, it is partly only output at the element and not at the label or vice versa
* no consistent output between the different browsers

I have chosen checkboxes and selects as sample elements. The problems occur analogously with other form fields. But I did not test them systematically. My impression is that radio buttons behave like checkboxes and all other elements like select. A special case are input fields, because the screenreader changes to form mode. Then the output becomes even more inconsistent. 

The effects of the incorrect output are minimal if the labeling is correct: labeling in the source code 
* directly before (all form fields except radio buttons and checkboxes) or 
* directly after (radio buttons and checkboxes) 

the form field. 

JAWS output at this point is significantly better than the label output of NVDA.

#### form field type
* checkbox: Label is always output directly at the form element (IE 11, Firefox, Chrome)
* select: Label is not output together with the form element, but before, after (IE 11, Firefox, Chrome), or even not at all with the element (IE 11, Chrome)

#### labeling method
* label for and select: no output at the element (IE 11, Chrome)
* aria-labelledby and select: no output at the element (IE 11)

#### Form field and label in source code separated from each other
* label for and checkbox: no output of the label at the position of the label (IE 11, Chrome)

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by stevefaulkner** [comment]
@JAWS-test Closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).

**Comment by JAWS-test** [comment]
@stevefaulkner 

Tested with current Chrome and JAWS 2024: label and label for: What has not changed is that the labelling for checkboxes and radio buttons is output with the element, but not at the point where it is located in the source code. For all other form elements, the label is output at the position in the source code, but not at the element. Where does this inconsistency come from?
