### ISSUE TITLE
Invalid child elements are output

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#307]
### Summary

Invalid child elements are output

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Required Owned Elements</title>
	</head>
	<body>
		<div role=listbox aria-multiselectable=true>
			<h2>h2</h2>
			<div role=option>option 1</div>
			<div role=option aria-selected=true>option 2</div>
			<div role=option>option 3</div>
			text
		</div>
		<div role=grid>
			<h2>h2</h2>
			<div role=row>
				<div role=gridcell>gridcell 1</div>
				text
				<div role=gridcell>gridcell 2</div>
			</div>
			text	
			<div role=row>
				<div role=gridcell>gridcell 3</div>
				<div role=gridcell>gridcell 4</div>
			</div>
		</div>	
	</body>	
</html>
```
2. read with arrow keys

### Expected result
* Consistent output between different browsers
* Invalid child elements are not output

### Actual result 
* IE 11: Invalid child elements are always output (example listbox and grid)
* Firefox, Chrome: Invalid child elements are sometimes output (with grid, but not with listbox)

See: https://github.com/w3c/aria/issues/1028

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by stevefaulkner** [comment]
@JAWS-test Closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).
