### ISSUE TITLE
iFrames are not output correctly if they are within hidden areas (Chrome, IE 11)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#309]
### Summary

iFrames are not output correctly if they are within <code>visibility:hidden</code> areas (Chrome, IE 11)

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>visibility</title>
	</head>
	<body>
		<button>test</button>
		<div style="visibility:hidden;">
			<iframe src="https://freedomscientific.github.io/VFO-standards-support/html.html" style="visibility:visible;"><!--iFrame-->test</iframe>
		</div>
	</body>
</html>
```
2. Tab to the interactive elements inside the iFrame
3. Use arrow keys to read the content of the iFrame

### Expected result

Correct output of the iFrame content

### Actual result 

* The content is not output correctly if the <code>visibility:visible</code> is located on the iFrame.
* The content is output correctly if <code>visibility:visible</code> is located on an ancestor element of the iFrame.

#### Chrome
* reading with arrow keys: ok
* Tab navigation: no output

#### IE 11
* reading with arrow keys: no output of the iFrame, but output of invisible content inside the iFrame element (including the HTML commments)
* Tab navigation: output of the last element outside the hidden area (button "test")

#### Firefox
ok

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 76.0.3809.132
Firefox ESR 60.8.0
IE 11.1268.16299.0

**Comment by stevefaulkner** [comment]
@JAWS-test Closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).
