### ISSUE TITLE
Nested visibility:hidden are not output correctly

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#312]
### Summary

Nested visibility:hidden are not output correctly if it is referenced by aria-labelledby

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>visibility:hidden</title>
	</head>
	<body>
		<div id=1>
			outside
			<div id=2 style="visibility:hidden;">
				hidden 1
				<div id=3 style="visibility:visible;">
					inside
					<div id=4 style="visibility:hidden;">
						hidden 2
					</div>
				</div>
			</div>
		</div>
		
		<input aria-labelledby=1>
		<input aria-labelledby=2>
	</body>
</html>
```
2. Use quick navigation (E)
3. Use element overview (INS+Ctrl+E)
4. Navigate with Tab key
5. read with arrow keys

### Expected result

According to https://www.w3.org/TR/accname-1.1/

1: outside inside
2: hidden 1 inside

See also: https://github.com/w3c/accname/issues/57

#### Firefox
1: outside inside
2: hidden 1 inside hidden 2 

#### Chrome, IE 11, Edge

1. outside 
2. hidden 1 inside

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 76.0.3809.132
Firefox ESR 60.9.0
IE 11.1331.16299.0
Edge 16.16299

**Comment by stevefaulkner** [comment]
@JAWS-test Closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).
