### ISSUE TITLE
img with a ARIA role is output as graphic

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#314]
### Summary

img with a ARIA role is output as graphic

1. save as HTML file:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>img</title>
	</head>
	<body>
		<img src=1 aria-label=checkbox1 role=checkbox tabindex=0>
		<img src=2 alt="II" aria-label=checkbox2 role=checkbox tabindex=0>
		<img src=3 aria-label=link1 role=link  tabindex=0>
		<img src=4 alt="IV" aria-label=link2 role=link  tabindex=0>
		<img src=5 aria-label=textbox1 role=textbox  tabindex=0>
		<img src=6 alt="VI" aria-label=textbox2 role=textbox  tabindex=0>
		<img src=7 aria-label=button1 role=button  tabindex=0>
		<img src=8 alt="VIII" aria-label=button2 role=button  tabindex=0>
	</body>
</html>
```
2. Use quick navigation (G)
3. Use element overview (INS+Ctrl+G)

### Expected result

No output of images because of ARIA roles

### Actual result 

* Chrome, Firefox: Output of all images (with G and INS+Ctrl+G)
* IE 11: Output of all images except image with <code>role=textbox</code> (with G and INS+Ctrl+G)
* Edge: No output of images
* Firefox: Output of graphics with different labels in the element overview depending on the ARIA role (aria-label, alt, src). With IE 11 and Chrome, only aria-label is displayed
* No output as graphic when reading with arrow keys and tab navigation

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 76.0.3809.132
Firefox ESR 60.9.0
IE 11.1331.16299.0
Edge 16.16299

**Comment by stevefaulkner** [comment]
@JAWS-test I have found that the images can still be navigated with the G key (IE11 and chrome tested), they are announced with their assigned ARIA roles. What I am unclear about is whether this is an issue that rises to the level of a bug that needs to be fixed. While the roles are allowed on <img>, unless they are found to be used frequently in the wild I would file this under an edge case with minimal real world effect.

**Comment by JAWS-test** [comment]
I consider this a bug because <code>img</code> with <code>role=button</code> is common. When I use G to navigate to graphics or INS+CTRL+G to output a list of all graphics, it is very confusing that
1. there seem to be many graphics available which are not output during tab navigation or when reading with the arrow keys 
2. the graphics are not output as graphics

**Comment by JAWS-test** [comment]
> I created a test page with quoted attributes and img source, to remove any possible effects the markup may have on JAWS output.

Thanks!
* unknown img source: has the effect that the elements are output as "disabled"
* no quotes: is valid HTML source code and should not have any effect

**Comment by stevefaulkner** [comment]
> I consider this a bug because img with role=button is common.

@JAWS-test I didn't say it wasn't a bug, what I was musing on was; given there are many bugs documented, does this particular bug cause an issue that makes the content less accessible, and does it occur frequently enough that fixing it would improve the accessibility of the user experience sufficiently to warrant it being fixed over other bugs.

**Comment by JAWS-test** [comment]
I agree. This is one of the most unimportant bugs.
