### ISSUE TITLE
Nested list entries are skipped with quick navigation

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#317]
### Summary

Nested list entries are skipped with quick navigation

1. save as HTML file or go to https://codepen.io/jaws-test/pen/RwwwaQW:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>list</title>
	</head>
	<body>
		<ul>
			<li>1
				<ul>
					<li>1a
					<li>1b
				</ul>
			<li>2
		</ul>
	</body>
</html>
```
2. Use quick navigation (I)

### Expected result

* Nested list entries are output with quick navigation
* The hierarchy of the nested list is output when entering it

### Actual result 

* Nested list entries are skipped with quick navigation
* The problem also occurs if one is already in the nested list
* The problem occurs with all tested browsers
* The problem does not occur with older versions of JAWS (for example, JAWS 18). Note: The hierarchy of the list was not output, but "New list"
* The problem does not occur if the list entries are nested incorrectly, i.e. if <code>ul</code> is a direct child element of <code>ul</code>

#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 76.0.3809.132
Firefox ESR 60.9.0
IE 11.1331.16299.0

**Comment by stevefaulkner** [comment]
@JAWS-test closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).

**Comment by JAWS-test** [comment]
@stevefaulkner Again, the ticket was only closed because it is old and not because the problems have been fixed. I have retested it with Chrome and JAWS 2024 - the problems remain unchanged. I have no objection if the ticket remains closed because it is minor and I can also reach the nested lists with quick navigation using L
