### ISSUE TITLE
JAWS [VC] doesn't narrate menu item, when it is open from menu button

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/standards-support#324]
### Summary

 
Example:
Use JAWS in Virtual Cursor mode.
1.Go to https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html
2.  Navigate in virtual cursor mode into "WAI-ARIA Quick Links" button
3. press enter 
4. observe JAWS narration

### Expected result
JAWS should narrate menu item "W3C Home Page"

### Actual result
JAWS narrate:
menu
WAI-ARIA Quick Links menu
WAI-ARIA Quick Links 
To navigate press Up or Down Arrow

### Example
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html

#### JAWS version and build number
2019.1909.28
Serial Number: 32810
 
#### Operating System and version
Win 10 Enterprise
Version: 1903

#### Browser and version:
Chrome 77.0.3865.90

**Comment by JAWS-test** [comment]
* The problem only occurs in Chrome. In IE 11 and Firefox the output is correct.
* The problem also occurs in Chrome when the button to open the menu is focused with the tab key

**Comment by stevefaulkner** [comment]
Closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).
