### ISSUE TITLE
The enumeration characters in lists are not output correctly

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#333]
### Summary

The enumeration characters in lists are not output correctly.

1. Go to https://codepen.io/jaws-test/pen/zYYxWeY
2. Navigate with I to the list entries or read with arrow keys

### Expected result
* No output of enumeration characters at `ul` (and `menu`), because they are purely decorative
* Correct output of all enumeration characters at `ol`, because they transmit relevant information (if the output is not possible, the corresponding number should be output instead)

### Actual result 
* Output of enumeration characters at `ul`
* Partially no or wrong output of the enumeration characters with `ol`

See also: 
* https://github.com/w3c/html-aam/issues/256
* https://github.com/FreedomScientific/VFO-standards-support/issues/332 and https://github.com/FreedomScientific/VFO-standards-support/issues/331
* https://github.com/w3c/aria/issues/961

#### Chrome
* The graphic enumeration signs are always output as "bullet", "hollow round" and "blank square", although their representation is purely decorative
* `lower-roman` are output as letters instead of numbers
* No output of `georgian`, `armenian` and `cjk-ideographic`

#### Firefox 
* The graphic enumeration signs are always output as "bullet", "hollow round" and "blank medium small square", although their representation is purely decorative
* `georgian`, `armenian`, `hebrew` are output as numbers instead of letters

#### IE 11
* `lower-roman` are output as letters instead of numbers
* at `ol` all but `decimal` and `lower-roman` are output as "bullet
	
#### JAWS version and build number

JAWS 2019.1907.42
 
#### Operating System and version

Windows 8

#### Browser and version:

Chrome 76.0.3809.100
Firefox 68.0.2
Internet Explorer 11.0.9600.19431

**Comment by stevefaulkner** [comment]
@JAWS-test closing this, please feel free to re-open if this still occurs with Latest (JAWS 2024).

**Comment by JAWS-test** [comment]
@stevefaulkner Again, the ticket was only closed because it is old and not because the problems have been fixed. I have retested it with Chrome and JAWS 2024 - the problems remain unchanged
