### ISSUE TITLE
Input fields for passwords are not output correctly when reading with the arrow keys

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#336]
### Summary

Input fields for passwords are not output correctly when reading with the arrow keys

1. Go to https://codepen.io/jaws-test/pen/XWWmLmV
2. Read with arrow keys

### Expected result

* Role is output 1x
* The role of the input field after the password field is output correctly

### Actual result

* Role is output up to 8 times
* The input field after the password field is also output as a password field (Chrome, Firefox)

The problem occurs only if the automatic switch to forms mode for input fields is not disabled.

#### JAWS version and build number

JAWS 2019.1909.28
 
#### Operating System and version

Windows 10

#### Browser and version:

Chrome 76.0.3809.132
Firefox ESR 60.9.0
IE 11.1331.16299.0

**Comment by stevefaulkner** [comment]
tested using [https://cdpn.io/pen/debug/GRLOOmo](https://cdpn.io/pen/debug/GRLOOmo) JAWS 2024.2403.3 and Chrome  Version 123.0.6312.86 (Official Build) (64-bit) could not reproduce
