### ISSUE TITLE
Enter into a tablist JAWS narrates: To switch pages, press Control+PageDown 

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/standards-support#337]
### Summary

Example:
Precondition: VC is off
Steps to reproduce:
1. Go to aria example https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html

2. Navigate into the tab under the: "Example of Tabs with Manual Activation"

3. Observe the JAWS narration

### Expected result
JAWS should not narrate instruction message "To switch pages, press Control+PageDown."
The shortcut "Control+PageDown" is switching between the tabs in the browser, not sure why the same shortcut should change tabs in the tablist on the webpage.

### Actual result
JAWS narate: "Entertainment Tab Nils Frahm Tab selected 1 of 3 To switch pages, press Control+PageDown."

### Example
https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html

#### JAWS version and build number
Version: 2019.1909.28

 
#### Operating System and version
Windows 10 Enterprise
version: 1903

#### Browser and version:
Chrome 77.0.3865.90

**Comment by JAWS-test** [comment]
I can confirm the bug. It only occurs in Chrome and not in IE 11 or Firefox.

**Comment by ghost** [comment]
Hi @kolaps33 
A possible solution is
1.  Press "INSERT +Z" to activate the JAWS cursor
2. Click on JAWS -> Options-> Basic Settings->Turn off menu and control help
