### ISSUE TITLE
links, form fields and buttons in legend are not recognized (IE 11, Chrome, Firefox, Edge)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#402]
### Summary

A link in the legend element of a fieldset is not output 

1. Go to https://codepen.io/jaws-test/full/wvMmVoJ
2. Tab + Shift-Tab to the link in the legend of the fieldset
3. Press INS+F7 (link overview)
4. Read with virtual cursor

The same is true for buttons (also tested) and probably for other interactive elements (not tested)

### Expected result

Correct output of the link

### Actual result

* Tab navigation: Instead of the link, the name, role and value of the previously focused element is output. The JAWS cursor remains on the previously focused element, so that when you operate the link, the previously focused element is operated instead of the link.
* No link in link overview (INS+F7).
* No output of the link with virtual cursor.

This problem occurs in IE 11, Chrome, and Firefox. 

The problem is serious and should be fixed soon

Related: https://github.com/FreedomScientific/VFO-standards-support/issues/100

#### JAWS version and build number

JAWS 2020.2003
 
#### Operating System and version

Windows 10

#### Browser and version:

Current version of IE 11, Chrome and Firefox ESR

**Comment by lamador** [comment]
The issue was reproducible using the latest version of JAWS (2020.2006.12), Chrome (84.0.4147.89), Firefox (78.0.2), and IE11 (11.959.18362.0).

**Comment by JAWS-test** [comment]
The problem also exists with form fields in legend. These are neither output in form mode nor with the virtual cursor. Thus, for example, the [second and third WHATWG fieldset examples](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element) do not work. These examples are neither perceptible nor operable with JAWS. The problem occurs with JAWS 2021 and Firefox, Chrome, Edge.

**Comment by JAWS-test** [comment]
The problem does not occur with NVDA. Also in the Accessibility API of the browsers the information is transmitted correctly

**Comment by SparrowSpit** [comment]
Any word on if this may be fixed in upcoming releases?

**Comment by scq** [comment]
This is still broken in JAWS 2024.2310.70.

@stevefaulkner sorry to bother, but do you know if this is on Freedom Scientific/Vispero's radar at all?

**Comment by JAWS-test** [comment]
Tested with JAWS 2023:
* The problem no longer occurs with buttons
* The problem still occurs with links

**Comment by JAWS-test** [comment]
@stevefaulkner As the problem is very serious, please resolve it as soon as possible. The ticket is 4 years old, the problem is much older...

**Comment by stevefaulkner** [comment]
@JAWS-test have made it a high priority issue and assigned it to @BrettLewisVispero /cc @ggordon-vispero @RFischer-FS

**Comment by BrettLewisVispero** [comment]
Imported into ADO as bug 76984
