### ISSUE TITLE
Form elements with disabled and aria-disabled are not output correctly (IE, Chrome)

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#413]
### Summary

Form elements with disabled and aria-disabled are not output correctly (IE, Chrome). 

1. Go to https://codepen.io/jaws-test/pen/pogYLKw
2. Press INS+F5
3. read with arrow keys

### Expected result

The ARIA specification specifies that if there is a conflict between HTML and ARIA attribute, the HTML attribute takes precedence and the ARIA attribute is ignored. This means that elements with disabled and aria-disabled=false must be output as disabled (see https://github.com/w3c/html-aam/issues/294)

### Actual result

* Firefox: ok
* IE 11 and checkbox: wrong status (output as "not checked", although checked)
* Chrome and select or edit: no output of the form field
* Chrome and checkbox: no output of the status disabled

The errors in Chrome are partly due to the fact that Chrome does not correctly report the status disabled, but the fact that the form elements are not output at all is a JAWS bug. Additionally, I think that JAWS should not rely solely on the Accessibility API, but should evaluate the DOM 

#### JAWS version and build number
JAWS 2020.2003
 
#### Operating System and version
Windows 10

#### Browser and version:
current version of IE 11, Firefox ESR, Chrome

**Comment by frex65** [comment]
@BenKeyFSI  @kurtjwolf  this bug can be replicated using JAWS 2020.2004.06 and Chrome 84.

**Comment by stevefaulkner** [comment]
tested with JAWS 2024.2405.48 and latest Chrome, works as expected
test case: https://cdpn.io/pen/debug/dyEMJPj
