### ISSUE TITLE
JAWS duplicate announcement for aria-setsize and aria-posinset attributes in IE11

### ISSUE THREAD

**Issue by bethwhitmer** [FreedomScientific/standards-support#451]
### Summary
We have a menubar with aria-setsize and aria-posinset attributes defined. In IE11, JAWS announces these values twice (e.g. it'll say "1 of 5 1 of 5". I am able to reproduce this issue in the ARIA Authoring Practices if I do the following:

1. Navigate to the following page in IE11: https://www.w3.org/TR/wai-aria-practices-1.2/examples/menubar/menubar-1/menubar-1.html
2. Add aria-setsize="3" and aria-posinset="1" to the About menu item.
3. Tab to the About menu item in IE11 and observe that an echo is announced (e.g. "1 of 3 1 of 3"). 

### Expected result

This "echo" does not occur in Chrome. I expect JAWS only to announce "1 of 3" once. 

### Actual result

JAWS in IE11 announces the value twice - e.g. "1 of 3 1 of 3"

### Example

https://www.w3.org/TR/wai-aria-practices-1.2/examples/menubar/menubar-1/menubar-1.html (you need to add-in the aria-setsize and aria-posinset attributes)

### Additional Information

We randomly discovered that this issue goes away if you define aria-describedby on the menu item. Then the "1 of 3" is only announced once as expected. 

#### JAWS version and build number

JAWS 2020.2008.24 ILM
 
#### Operating System and version

Windows 10

#### Browser and version:

IE11 latest

**Comment by StephenBeckettTPGi** [comment]
Bug confirmed using JAWS 2020.2008.24 ILM with IE11. 

FF81, Chrome 85.0.4183.121, and MS Edge do not have this behaviour.

Also confirm adding aria-describedby causes the issue to disappear (but not aria-labelledby, aria-label)

**Comment by stevefaulkner** [comment]
closing as IE only so wontfix
