### ISSUE TITLE
Aria-Details entry exit notices occur *within* the details if the details include containers

### ISSUE THREAD

**Issue by SuzanneTaylor** [FreedomScientific/standards-support#452]
### Summary

JAWS announces entering and exiting what is pointed to by aria-details. This is excellent and very important in academic settings, so that students know what info comes from an image description and what info comes from other text. This distinction is essential to some common core learning objectives.

However, when the aria-details includes certain containers, JAWS sees the boundaries of the containers as places where the details end and begin again. 

### Example:

1. Running JAWS (2018, 2019 or 2020) with Chrome, go to [http://manateeroad.com/BugReports/aria_details.html](http://manateeroad.com/BugReports/aria_details.html)
2. Everything after the image on this page is the aria-details. Use the down arrow to read the image and to continue reading down the page through the details.
3. Notice that JAWS says "Entering Details" and "Leaving" multiple times _within_ the details

### Expected result

JAWS should say only say "Entering Details" when entering the details from any direction and "Leaving" when leaving the details from any direction, as it does currently. But, the extra announcements within the details should not be present.

### Actual result

There are 3 unnecessary and potentially confusing additional announcements of "Leaving" and "Entering Details" within the description for this image.

#### JAWS version and build number
Most recently seen using 2020.2008.24 but had also been seen last year while testing with 2018 and 2019

#### Browser and version:
Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by frex65** [comment]
JAWS says "Leaving" when it is describing a container with a role such as "list with 3 items" or "table with 3 columns and 3 rows", then says "Entering details" again once it's inside the container and reading data.

**Comment by StephenBeckettTPGi** [comment]
Bug confirmed using JAWS 2020.2008.24 with:

- FF81, 
- Chrome 85.0.4183.121, 
- IE11 
- latest version of MS Edge

**Comment by stevefaulkner** [comment]
tested in JAWS 2024.2405.48 and latest Chrome/Firefox. Works as expected
