### ISSUE TITLE
JAWS exits forms mode when focus moved to checkbox in a toolbar

### ISSUE THREAD

**Issue by kt398** [FreedomScientific/standards-support#708]
### Summary
JAWS exits forms mode when focus moved to checkbox in a toolbar
 
> Example:
> 1. Go to [https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/examples/toolbar/](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/examples/toolbar/) with JAWS on
> 2. Using virtual cursor, navigate to the "Open in CodePen" button, and then tab into the toolbar.
> 3. Use left/right arrow keys to navigate to the "Night Mode" checkbox.
> 4. Observe that JAWS leaves forms mode, and arrow keys can't be used to navigate between elements in the toolbar

### Expected result

> JAWS stays in forms mode.

### Actual result

> JAWS switches to virtual-cursor mode, and left/right arrow keys can't be used to move between elements in the toolbar.

#### JAWS version and build number
JAWS 2023.2212.23 ILM

 
#### Operating System and version
Windows 10 21H2

#### Browser and version:
Microsoft Edge Version 111.0.1661.54 (Official build) (64-bit)
Chrome Version 111.0.5563.147 (Official Build) (64-bit)

**Comment by JAWS-test** [comment]
I can confirm the problem.

The problem also occurs with older JAWS versions.

The problem does not occur with NVDA.

The problem is not limited to checkboxes, but also occurs with links (in the example the "Help" link)

**Comment by BrettLewisVispero** [comment]
Imported into ADO as bug 17972

**Comment by BrettLewisVispero** [comment]
I tested with the release version of jaws 2024 and can no longer reproduce.
