### ISSUE TITLE
dialog description is not included in the output

### ISSUE THREAD

**Issue by stevefaulkner** [FreedomScientific/standards-support#729]
### Summary

[Modal Dialog Example](https://deploy-preview-237--aria-practices.netlify.app/aria/apg/patterns/dialog-modal/examples/dialog/) support table.

The dialog has one test with a required assertion that fails in Firefox.
Test: Open a nested modal dialog using a link in interaction mode
Command: After opening the dialog with Enter, the dialog description is not included in the output.

### Expected result

> dialog description is included in the output.

### Actual result

> dialog description is not included in the output.

### Example

https://cdpn.io/pen/debug/VwVydxv

#### JAWS version and build number
2023.2306.38

#### Operating System and version
Windows 10

#### Browser and version:
Firefox 115.0

**Comment by BrettLewisVispero** [comment]
Imported into ADO as bug 37914

**Comment by BrettLewisVispero** [comment]
Fixed in JAWS 2024
