### ISSUE TITLE
Insert+Up does not announce the slider accessible name

### ISSUE THREAD

**Issue by stevefaulkner** [FreedomScientific/standards-support#730]
### Summary

[Color Viewer Slider Example](https://deploy-preview-237--aria-practices.netlify.app/aria/apg/patterns/slider/examples/slider-color-viewer/) support table

The slider has one test with a required assertion that fails in Firefox.
Test: Read information about a slider in reading mode
Command: Insert+Up does not announce the slider name

### Expected result

> Insert+Up announces the slider accessible name

### Actual result

> Insert+Up does not announce the slider accessible name

### Example

https://aria-at.netlify.app/tests/horizontal-slider/test-07-read-information-about-slider-reading-jaws.collected.html

#### JAWS version and build number
2023.2306.38

#### Operating System and version
Windows 10

#### Browser and version:
Firefox 115.0

**Comment by BrettLewisVispero** [comment]
This was fixed at the same time as #727.
