### ISSUE TITLE
JAWS 2023 is not  recognising role tablist when focus enters the wheel

### ISSUE THREAD

**Issue by Akhil-TI** [FreedomScientific/standards-support#731]
## Description of the issue
the following issue is observed only in jaws 2023, we tested with jaws 2022 and NVDA, they work fine.
We have a circular tab section, as the focus enters tablist its not recognizing it  by its role and reads it as regular headings.
it works if after pressing "enter", then forms mode is activated and functionality works as expected.

## Steps to reproduce the issue

-  working  example  : [example](https://svg-tablist-dfgags.stackblitz.io) 
-  stackblitz code: [stackblitz code](https://stackblitz.com/edit/svg-tablist-dfgags?file=src%2Fapp%2Ftablist%2Ftablist.component.html)

## Actual vs expected behaviour
Jaws should Identify the code from role=tablist and then should work as expected

## Environment (where applicable)
 
- JAWS version: jaws 2023
- Operating system: windows/Mac,
- Browser: Chrome, brave
- Browser version: latest (Version 114.0.5735.199 (Official Build) (64-bit))

**Comment by stevefaulkner** [comment]
@Akhil-TI 

- JAWS treats `tablist` as a `role=group`
- `role=group` is not announced unless it has an accessible name
- adding an accessible name to the element with `role="tablist"` results in JAWS announcing the group and name when navigating into/out of the group

`<svg ... role="tablist" ... aria-label="poot">`
