### ISSUE TITLE
In VPC mode, arrow key navigation doesn't focus on next elements, causing unexpected behavior.

### ISSUE THREAD

**Issue by gt106551** [FreedomScientific/standards-support#737]
### Summary

> When VPC (Virtual PC Cursor) mode is active, arrow keys are being used to navigate through content, but they're not setting focus on the next button or element in the group, leading to unexpected behavior.

> 
> Example:
> 1. Go to https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_button_group_justified2&stacked=h
> 2. Navigate till Button Group(Apple) and press down arrow key 

### Expected result

> In VPC mode, when using arrow keys to navigate through elements like Button groups, Checkbox fields, and Radio fields, the expected behavior is that focus should be set on the next element as the arrow keys are pressed.

### Actual result

> The actual behavior is that arrow keys in VPC mode do not set focus on the next element in the group. Instead, they read the content of the next element without actually focusing on it.

#### JAWS version and build number
           
           JAWS 2023.2303.144

 
#### Operating System and version

          Windows 10 Enterprise

#### Browser and version:

          Edge Browser Version 115.0.1901.188 (Official build) (64-bit)

**Comment by stevefaulkner** [comment]
@gt106551 
> In VPC mode, when using arrow keys to navigate through elements like Button groups, Checkbox fields, and Radio fields, the expected behavior is that focus should be set on the next element as the arrow keys are pressed.

in VPC mode JAWS is navigating a copy of the DOM. It does focus the buttons in the virtual copy when navigating via the up/down arrow keys.
