### ISSUE TITLE
duplicated content announcement

### ISSUE THREAD

**Issue by stevefaulkner** [FreedomScientific/standards-support#738]
### Summary
In the test case JAWS announces "red" 3 times on successive down arrow presses. The second announcement is not from the DOM content or the acc tree content. 
reported in https://aria-at.w3.org/report/1904/targets/161#result-ODA1ZeyIxMiI6NDAyfQjMzN2

Example:
1. Go to https://www.w3.org/WAI/ARIA/apg/patterns/slider/examples/slider-color-viewer/
2. move to heading level 3 "Color Viewer"
3. press arrow down key 3 times and observe output

### Expected result

In the test case JAWS announces the following on arrow down
1. red (from visible text)
2. red (accessible name for role=slider) left right slider 128 min 0 max 255

### Actual result

In the test case JAWS announces the following on arrow down
1. red (from visible text)
2. red (from who knows where?)
3. red (accessible name for role=slider) left right slider 128 min 0 max 255

### Example

[test case](https://www.w3.org/WAI/ARIA/apg/patterns/slider/examples/slider-color-viewer/)

#### JAWS version and build number
2023.2307.37

 
#### Operating System and version
windows 10

#### Browser and version:
chrome Version 115.0.5790.171 (Official Build) (64-bit)

/cc @RFischer-FS

**Comment by BrettLewisVispero** [comment]
Imported into ADO as bug 48452
