### ISSUE TITLE
insertion and deletion are not output by JAWS 2023

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#749]
### Summary

1. Go to https://codepen.io/jaws-test/pen/rNoWJGB
2. Read with arrow keys

### Expected result

Insertion and deletion is output with the ARIA 1.2 roles in the same way as with the corresponding HTML elements

### Actual result

Insertion and deletion is not output with the ARIA 1.2 roles. The HTML elements are output correctly by JAWS.

NVDA outputs the ARIA 1.2 roles correctly

#### JAWS version and build number
JAWS 2023.2307.37
 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome 116.0.5845.142
Firefox 116.0.3

**Comment by stevefaulkner** [comment]
tested as above, same result - updated https://www.tpgi.com/screen-readers-support-for-text-level-html-semantics/ to accurately reflect JAWS 2023.2307.37

**Comment by BrettLewisVispero** [comment]
Fixed in the next release of JAWS 2024.
