### ISSUE TITLE
 strong and emphasis are not output by JAWS 2023

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#750]
### Summary

1. Go to https://codepen.io/jaws-test/pen/WNLozeB
2. Change speech and sound scheme to "Proofreading (Attribute)" (see https://github.com/FreedomScientific/standards-support/issues/668#issuecomment-1251072074)
3. Read with arrow keys

### Expected result

strong and emphasis is output with the ARIA 1.2 roles in the same way as with the corresponding HTML elements

### Actual result

strong and emphasis is not output with the ARIA 1.2 roles. The HTML elements are output correctly by JAWS.

#### JAWS version and build number
JAWS 2023.2307.37
 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome 116.0.5845.142

**Comment by stevefaulkner** [comment]
tested as above and got same result

**Comment by BrettLewisVispero** [comment]
Imported into ADO as bug 41798

**Comment by BrettLewisVispero** [comment]
Fixed in the next build of JAWS 2024
