### ISSUE TITLE
blockquote is not output by JAWS 2023

### ISSUE THREAD

**Issue by JAWS-test** [FreedomScientific/standards-support#751]
### Summary

1. Go to https://codepen.io/jaws-test/pen/xxmRWwr
2. Read with arrow keys

### Expected result

blockquote is output with the ARIA 1.2 role in the same way as with the corresponding HTML element

### Actual result

blockquote is not output with the ARIA 1.2 role. The HTML element is output correctly by JAWS.

NVDA outputs the ARIA 1.2 role correctly

#### JAWS version and build number
JAWS 2023.2307.37
 
#### Operating System and version
Windows 10

#### Browser and version:
Chrome 116.0.5845.142
Firefox 116.0.3

**Comment by stevefaulkner** [comment]
tested as above and got same result

**Comment by BrettLewisVispero** [comment]
Fixed.
