### ISSUE TITLE
combobox operation error by JAWS 2023

### ISSUE THREAD

**Issue by Ignacio-de-Loyola** [FreedomScientific/standards-support#760]
### Summary

When navigating the list using the down arrow key in a combo box, a specific list may be skipped.
This error can only be seen in JAWS 2023 version.
Screen Example : https://drive.google.com/file/d/1cdUpCiUjJcuS_FBVTrGrR_s4lBWWGrCS/view?usp=sharing

### What did you expect to happen?

The user has to check the combobox list one by one.

### What actually did happen?

When users navigate a combo box list, they are skipping parts of the list.

Example : https://www.koreanair.com 
(Search origin/destination Combobox)

**JAWS version and build number**
2023.23.07.37

**Operating System and version**
Windows 11

**Browser and version:**
Chrome 117.0.5938.89

**Comment by JAWS-test** [comment]
I can confirm the error:
* when navigating through the list with the arrow keys, every second entry is skipped with JAWS
* When entering the list, the first entry is also skipped, but JAWS outputs the first and second list entry.

The error does not occur with NVDA.
The error does not occur without a screen reader.

**Comment by Ignacio-de-Loyola** [comment]
Is there any way I can fix this? Or is it a problem with JAWS?
