### ISSUE TITLE
In Virtual Cursor mode, JAWS does not emit number of options for unfocused listboxes

### ISSUE THREAD

**Issue by Vladimir-Goncharov-a11y** [FreedomScientific/standards-support#765]
### Summary
1. Rename an extension of the attached sample file from .txt to .html; Open the sample in Chrome.
[odan_397_GitHub_765.txt](https://github.com/FreedomScientific/standards-support/files/12705670/odan_397_GitHub_765.txt)
2. Set PC focus to the first edit field.
3. Switch JAWS to Virtual PC Cursor mode (NumPad-Plus)
4. Press the down arrow key multiple times to get the following JAWS transcript

--- JAWS transcript begins ---
> The First Registry
>  List box

--- end of JAWS transcript ---

### Expected result
I would expect to have the number of available options in the select list, like JAWS does in Forms mode:
--- Expected JAWS transcript begins ---
> The First Registry
>  List box with 2 items

--- end of the expected JAWS transcript ---

### Actual result
Presently, it is not possible to understand with JAWS how many options available in the listbox without interacting with the list box.
JAWS does emit the number of items in the Forms mode when users Tab into the list box focusing the list box item. JAWS says in Forms mode something like "List with 2 items"
Also, when one of listbox items is focused then JAWS, even in Virtual Cursor mode and,  emits the number of items by saying something like "1 of 2".

### Additional Information
The bug is reproducible with the default JAWS settings (Insert-Space, z)
The bug is reproducible in JAWS 2023 August release.
The bug is reproducible with JAWS 2024 beta September release.

#### JAWS version and build number
Version Details Information:
JAWS version 2023.2307.37.400
JAWS version 2024.2308.124.400 

#### Operating System and version
Microsoft Windows 10 Professional Version 22H2 (OS Build 19045.3448), System Type x64 

#### Browser and version:
Google Chrome Version 116.0.5845.188

**Comment by JAWS-test** [comment]
I wouldn't call that a bug. It is the decision of JAWS which information is output for which navigation method. In VPC mode, the number of list entries is less important. A feature request could be to have an option in the settings that also in VPC mode all list entries are output by JAWS and their number + position. However, this option should not be activated by default.

Note: The number of list entries is also not output by NVDA in VPC mode.

**Comment by stevefaulkner** [comment]
agree with @JAWS-test closing
