### ISSUE TITLE
Inconsistent announcement of "Clear" button within search fields

### ISSUE THREAD

**Issue by Epic-Third-Party-Bug-Reporting** [FreedomScientific/standards-support#778]
### Summary

1.	Focus on the text box of a search field.
2.	Type anything.
3.	Arrow down when the next element is the clear button, usually an X on the right side of the search bar. You may have to type a lot of gibberish to avoid arrowing down to results.
4.	Notice no announcement or the announcement of something that isn’t the clear button.

### Expected result

The announcement of the clear button

### Actual result

No announcement or the announcement of something that isn’t the clear button.

### Example

Similar behavior is seen on [Yahoo Search - Web Search](https://search.yahoo.com/). NVDA seems to handle this case.

#### JAWS version and build number

2022.2211.7 ILM
 
#### Operating System and version

Windows 10 Enterprise

#### Browser and version:

Chrome 115.0.5790.110 (Official Build) (32-Bit)

**Comment by JAWS-test** [comment]
I do not have this problem with Chrome and JAWS. The Clear button is output correctly.

**Comment by stevefaulkner** [comment]
> Similar behavior is seen on [Yahoo Search - Web Search](https://search.yahoo.com/). NVDA seems to handle this case.

when investigating the yahoo search (JAWS 2024, chrome Version 119.0.6045.105 (Official Build) (64-bit))  I found that the clear button was not in the correct place in the tab order. 

![the search input is first in focus order, the clear button is seventh in focus order](https://github.com/FreedomScientific/standards-support/assets/835859/3639a792-52e3-4f82-825a-c52960f23fa6)

closing as not a JAWS bug
