### ISSUE TITLE
JAWS doesn't narrated column and row information with grid combo example

### ISSUE THREAD

**Issue by kolaps33** [FreedomScientific/standards-support#790]
### Summary

Example:
1. Go to the example: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/grid-combo/
2. Navigate into "Fruits and vegetables" combobox
 ![image](https://github.com/FreedomScientific/standards-support/assets/22620150/3a9e241f-886c-4d56-a4a6-f885f9ecdf30)
3. type letter 'a'
4. navigate into results
5. observe JAWS narration

### Expected result
JAWS should narrated row and column information, otherwise user doesn't know the position in the results... 

### Actual result
Apple selected
Artichoke selected
Asparagus selected

### Example
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/grid-combo/

#### JAWS version and build number
2023.2303.144

 
#### Operating System and version
Windows 11 Enterprise
Build: 22631.2715

#### Browser and version:
Chrome Version 119.0.6045.200 (Official Build) (64-bit)

**Comment by aardrian** [comment]
Using JAWS 2024 with Chrome 119 I hear the following as I arrow through:

> Fruits and vegetables table, Column 1, Row 1, Fruits and vegetables, 2 columns and 3 rows, Apple selected, col 1 row 1

 ↓

> Artichoke selected, Row 2

 ↓

>Asparagus selected, Row 3

Bear in mind that APG examples are typically not production-ready code (as it explains at the top of the page), so they may not behave as you expect. Using a `grid` role in this way may also not be ideal.

**Comment by stevefaulkner** [comment]
I tested it with JAWS 2024 and Chrome Version 119.0.6045.200 (Official Build) (64-bit) 
short video shows the expected behavior

https://github.com/FreedomScientific/standards-support/assets/835859/6248c6b1-8b7b-4629-a73c-d88a379c647b
