### ISSUE TITLE
Treeview content hidden in virtual mode

### ISSUE THREAD

**Issue by stevefaulkner** [FreedomScientific/standards-support#812]
### Summary

1. Go to https://cdpn.io/pen/debug/ExMzRBe
2. navigate using cursor keys to the treeview

### Expected result

the contents of the treeview is visible in virtual mode

### Actual result

the contents of the treeview is not visible in virtual mode

#### JAWS version and build number
JAWS 2024

 
#### Operating System and version

Windows 11

#### Browser and version:

Chrome Version 121 (Official Build) (64-bit)

**Comment by stevefaulkner** [comment]
discussed with @BrettLewisVispero @ggordon-vispero they think that:

1. there should be a tutor hint as to how to interact with a treeview
2. in the case of treeviews with nothing selected that the first item should be exposed in the virtual buffer.

**Comment by BrettLewisVispero** [comment]
Imported into ADO as bug 77593

**Comment by BrettLewisVispero** [comment]
This should be fixed.
