### ISSUE TITLE
JAWS key mapping conflict with defaults and outlook classic mappings

### ISSUE THREAD

**Issue by ros3cin** [FreedomScientific/standards-support#819]
### Summary

JAWS has an override for Outlook where the INSERT+Z keystroke - instead of turning the virtual PC cursor on/off - toggles the navigation mode on/off instead, and that only works on an open text area (like the email body). The same thing happening to other fields in outlook such as the 'To' and 'Cc' fields. 

Screenshots of the mapping below:
The default mapping for everything.
![image](https://github.com/FreedomScientific/standards-support/assets/1633894/3355aa05-3e2b-48f1-bf41-74363e8e9ce9)

The special mappings for outlook
![image](https://github.com/FreedomScientific/standards-support/assets/1633894/356d7e46-0084-48eb-8aa3-bc33630c9b35)

So one could change those mappings to find a new one for the navigationModeToggle for outlook. But even after changing that, the original virtualPcCursorToggle is still unresponsive.

### Expected result

Outlook specific mappings should not conflict with the default mappings. User should be able to normally toggle virtual PC cursor in Outlook using JAWSKey+Z.

### Actual result
JAWSKey+Z is overriden by Outlook specific mappings, so the shortcut doesn't toggle virtual PC cursor on/off.

#### JAWS version and build number
JAWS professional edition
Version 2024.2403.3
 
#### Operating System and version
OS Name Microsoft Windows 11 Enterprise
Version 10.0.22631 Build 22631

#### Browser and version:
Outlook classic on Windows

**Comment by stevefaulkner** [comment]
@ros3cin is this an issue on the desktop Outlook or the web based outlook?

**Comment by ros3cin** [comment]
@stevefaulkner this is on Outlook desktop (classic/win32 version)

**Comment by stevefaulkner** [comment]
Thanks @ros3cin, unfortunately this is not the place to file JAWS issues on desktop apps, cc’ing @RFischer-FS @BrettLewisVispero who will be able better direct your issue to the appropriate place.

**Comment by ros3cin** [comment]
@stevefaulkner gotcha. Thank you!
