### ISSUE TITLE
The dfn element is exposed in acc tree as role="term"

### ISSUE THREAD

**Issue by stevefaulkner** [FreedomScientific/standards-support#821]
### Summary

Example:
 1. Go to https://thepaciellogroup.github.io/AT-browser-tests/test-files/dfn.html
2. in test case note the Term "the internet" not conveyed as a term

### Expected result

term is identified as such, perhaps via user preference?

### Actual result

no identification of term

#### JAWS version and build number

JAWS 2024.2403.3
 
#### Operating System and version

Windows 11

#### Browser and version:

Chrome Version 123.0.6312.106 (Official Build) (64-bit)

**Comment by BrettLewisVispero** [comment]
Imported into ADO as bug 79621

**Comment by BrettLewisVispero** [comment]
After some internal discussion, we have decided not to support this at present. Most users think that there is little benefit to "know" what specifically is a term or definition.
The additional verbosity in a long list of terms and definitions would be irritating while not adding any information.
