### ISSUE TITLE
Nested Table Read Twice

### ISSUE THREAD

**Issue by BrysonRJones** [FreedomScientific/standards-support#842]
### Summary
I made a nested table to check how JAWS would handle it. JAWS reads through the nested table twice before announcing the end of the document. Within each of the last four cells, a label for a span is present. The span has no actual content and instead is provided an aria-label of "blank"

> Brief description of the issue. Please list any specific steps.
> 
> Example:
> 1. Go to http://www.google.com
> 2. Shift-Tab back to the About link

### Expected result
I'd expect the nested table to only be read through once.
> What did you expect to happen?

### Actual result
The nested table was read through twice.
> What actually did happen?

### Example
[JSBin](https://jsbin.com/fatelaf/edit?html,js,output)
> A test case that demonstrates the issue - provide linked test case, CodePen, JSbin, etc...

#### JAWS version and build number
JAWS 2023.2402.1

 
#### Operating System and version
Windows 11, 23H2

#### Browser and version:
Google Chrome, 124.0.6367.208

**Comment by stevefaulkner** [comment]
Thanks @BrysonRJones will look into it

Is this part of the test case code meant to be of any significance?

```
 <label for="4">Size</label>
                            <span id="4" aria-label="blank"></span>
```

**Comment by BrysonRJones** [comment]
There's no particular significance -- just labels with some text

**Comment by stevefaulkner** [comment]
@BrysonRJones I asked because the following code pattern is meaningless:

`label/for` will only label a  [labelable standard HTML element](https://html.spec.whatwg.org/multipage/forms.html#category-label) 

```html
<label for="1">Status</label>
<span id="1" aria-label="blank"></span>
```

**Comment by stevefaulkner** [comment]
I cleaned up the [test case](https://codepen.io/stevef/pen/VwJmqQN)

I cannot reproduce the issue with JAWS 2024.2406.121
