### ISSUE TITLE
Aria label not getting announced

### ISSUE THREAD

**Issue by kaustubh-vats** [FreedomScientific/standards-support#844]
### Summary

> Brief description of the issue. Please list any specific steps.
> I am using a JAWS version 2021, where I have added a div with tabIndex="0" and an aria label, the JAWS is reading the aria-label properly while navigating using tab keys. But on using JAWS version 2024, the aria label is not getting read out until I pass a role attribute along with the tabIndex=0. In JAWS 2024 version even if I pass role="region" then also the aria-label is not getting announced.

> Example:
> 1. [Go to https://jsfiddle.net/u1ntr8L0/2/](https://jsfiddle.net/u1ntr8L0/2/)

### Expected result

> The aria-label should get announced, when div is getting focus

### Actual result

> Aria label is not getting announced when div is in focus.

### Example
> Screen recordings:
> With JAWS 2021
[screen-capture (12).webm](https://github.com/FreedomScientific/standards-support/assets/55024026/3e3f44b6-50cf-4633-b8d0-94068558c92d)

> With JAWS 2024
[screen-capture (11).webm](https://github.com/FreedomScientific/standards-support/assets/55024026/c491229a-0f1a-47c5-a3d4-ba3c4a91ff0c)

#### JAWS version and build number
2021.2103.174
2024.2405.83

 
#### Operating System and version
Windows 11 Pro

#### Browser and version:
Google Chrome 125.0.6422.142 (Official Build) (64-bit) (cohort: Stable)

**Comment by JAWS-test** [comment]
No JAWS bus because a div is not allowed to have an aria-label: https://www.w3.org/TR/wai-aria-1.3/#generic

**Comment by JAWS-test** [comment]
Related: https://github.com/FreedomScientific/standards-support/issues/759

**Comment by kaustubh-vats** [comment]
@JAWS-test  any reasons why role="region" is also not working. Do we have any specific documentation or information related to what roles are supported for reading accessible names.

Example where role="region" is present but aria-label not getting announced
[screen-capture (13).webm](https://github.com/FreedomScientific/standards-support/assets/55024026/289af304-403b-441a-957a-958c6a07bb4f)

Also as this was not the behavior in earlier JAWS version, is there any release notes for the same?

**Comment by kaustubh-vats** [comment]
Figured out the role="region" is not getting announced because my verbosity level doesn't include Region. Enabling that worked here.
![image](https://github.com/FreedomScientific/standards-support/assets/55024026/9ed6fac2-efc4-4e84-bfb3-48b86ec2edb7)

Just wanted to know about this recent enhancement has any release notes as this was not happening earlier

**Comment by JAWS-test** [comment]
@kaustubh-vats 
I'm not from Freedom Scientific, so I can't tell you why JAWS outputs aria-label for some roles and not for others, and why the behavior has changed from version to version. I can only say with reference to the ARIA specification that certain ARIA roles / HTML elements cannot be labeled with aria-label and therefore JAWS itself does not make a mistake if it does not output the aria-label for these roles or elements

**Comment by stevefaulkner** [comment]
Thanks both
