### ISSUE TITLE
JAWS does not retrieve updates when using the "check for updates" option

### ISSUE THREAD

**Issue by MuffyOne** [FreedomScientific/standards-support#847]
Currently, the latest version of JAWS on the website is 2024.2406.121, I was running version 2024.2405.83, and my colleague's version  2024.2403.3. For both of us using the check for updates button always returned that we were on the latest versions and there were no updates available. 

The only way to update to the latest was to uninstall the software, download the latest from the website, and reinstall it

**Comment by stevefaulkner** [comment]
@MuffyOne closing this as its not a Web Standards related issue.
