### ISSUE TITLE
Radio button - twice announcement in VPC mode

### ISSUE THREAD

**Issue by havvamehfooz** [FreedomScientific/standards-support#849]
Summary :
Radio button is announced twice: once as unchecked and the second time as checked when navigated to the non -selected radio button with the virtual cursor and hitting enter key 

Example: 
It is reproducible in the ARG example: [Radio Group Example Using Roving tabindex | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/radio/examples/radio/).

Workflow:
-	Navigate to a non-selected radio button with the virtual cursor.
-	Hit enter

The result is that after enter the radio button is announced twice: once as unchecked and the second time as checked.
NVDA does not show such behavior. Issue is reproducible with Jaws 2024

**Comment by JAWS-test** [comment]
I can confirm the problem. It results from the mode change (VPC mode to forms mode):
* first ENTER causes the mode change and outputs the radio button
* then ENTER activates the radio button and outputs the status change

The problem can be avoided if the radio button is activated with SPACE. This would also be the normal operation of a radio button. 

Note: With JAWS 2023, the double output also occurs with ENTER, but 2x with the current status

**Comment by stevefaulkner** [comment]
> The problem can be avoided if the radio button is activated with SPACE. This would also be the normal operation of a radio button.

Thanks @JAWS-test, Not a bug.
